### ISSUE TITLE
Error when combining optional property and orderby

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1010]
Hi,
found an error with gravsearch when I try to order the result by using an optional property.
I think we could expect to get all the resources even all that do not have a date (at the end of the last page of course and not sorted) ? 

```sparql
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX onto: <http://0.0.0.0:3333/ontology/0001/anything/simple/v2#>

CONSTRUCT {
  ?thing knora-api:isMainResource true .
?thing onto:hasDate ?date .
} WHERE {
  
  ?thing a knora-api:Resource .
  ?thing a onto:Thing .
  
OPTIONAL {

?thing onto:hasDate ?date .
onto:hasDate knora-api:objectType knora-api:Date .
?date a knora-api:Date .

}

}
ORDER BY DESC(?date)
```
Error response:
`{
    "error": "org.knora.webapi.InconsistentTriplestoreDataException: entity http://rdfh.ch/0113/CQinAnP5TxmAY_2tEVacCA has no creator"
}`

**Comment by tobiasschweizer** [comment]
This is a bug, thanks for reporting it.

https://github.com/dhlab-basel/Knora/blob/3381d96dad8385e803f45902a5e5584c4583cc02/webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala#L2568

There is a pending refactoring of `SearchReponderV2`. I will have the reported problem as well.

**Comment by benjamingeer** [comment]
@tobiasschweizer says he will look at this, and by the end of next week he'll let you know how much time he needs to fix it.

**Comment by tobiasschweizer** [comment]
The Gravsearch query provided by you is converted into the following query executed by the triplestore:

```sparql
 SELECT DISTINCT ?thing (GROUP_CONCAT(DISTINCT(?date); SEPARATOR='') AS ?date__Concat)
 WHERE {
 ?thing <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#Resource> .
 GRAPH <http://www.ontotext.com/explicit> {
     ?thing <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
 ?thing <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/0001/anything#Thing> .
 OPTIONAL {
 ?thing <http://www.knora.org/ontology/0001/anything#hasDate> ?date .
 GRAPH <http://www.ontotext.com/explicit> {
     ?date <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
 }
 GRAPH <http://www.ontotext.com/explicit> {
     ?date <http://www.knora.org/ontology/knora-base#valueHasStartJDN> ?date__valueHasStartJDN .
 }
 }
 GROUP BY ?thing ?date__valueHasStartJDN
 ORDER BY DESC(?date__valueHasStartJDN) ASC(?thing)
 LIMIT 25
```

I am getting the following results for that query:

<img width="1772" alt="prequery" src="https://user-images.githubusercontent.com/6000023/50971724-08402a80-14e5-11e9-84ac-abd33475da82.png">

The same Iri for a date value appears again and again which is clearly wrong. I think this is because 

`?thing <http://www.knora.org/ontology/0001/anything#hasDate> ?date .` is contained in the `Optional` but `?date <http://www.knora.org/ontology/knora-base#valueHasStartJDN> ?date__valueHasStartJDN .` is not. As a consequence, `?date` can be unbound meaning that it could match anything.

I tried this:

```sparql
 OPTIONAL {
     ?thing <http://www.knora.org/ontology/0001/anything#hasDate> ?date .
     GRAPH <http://www.ontotext.com/explicit> {
         ?date <http://www.knora.org/ontology/knora-base#isDeleted> "   false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
     }
 
    GRAPH <http://www.ontotext.com/explicit> {
     ?date <http://www.knora.org/ontology/knora-base#valueHasStartJDN> ?date__valueHasStartJDN .
        }
}
```

I get the following results:

<img width="1785" alt="prequery2" src="https://user-images.githubusercontent.com/6000023/50971926-93b9bb80-14e5-11e9-9c48-1d7697026801.png">

This means that there is a bug when creating `?date <http://www.knora.org/ontology/knora-base#valueHasStartJDN> ?date__valueHasStartJDN`. This statement should be in the `Optional`, too.

The statement is generated here:

https://github.com/dhlab-basel/Knora/blob/05664eeaaa91f96f9d9b9db2f5248d4e29cbf73a/webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/prequery/NonTriplestoreSpecificGravsearchToPrequeryGenerator.scala#L132-L168

It is added to the `Where` clause here:

https://github.com/dhlab-basel/Knora/blob/05664eeaaa91f96f9d9b9db2f5248d4e29cbf73a/webapi/src/main/scala/org/knora/webapi/responders/v2/search/QueryTraverser.scala#L323

In this case, it cannot just be appended to the existing statements. It would have to be appended to the `Optional` contained in `transformedWherePatterns`:

```
Vector(
 StatementPattern(
 subj = QueryVariable(variableName = "thing"), 
 pred = IriRef(
 iri = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type".toSmartIri, 
 propertyPathOperator = None
 ), 
 obj = IriRef(
 iri = "http://www.knora.org/ontology/knora-base#Resource".toSmartIri, 
 propertyPathOperator = None
 ), 
 namedGraph = None
 ), 
 StatementPattern(
 subj = QueryVariable(variableName = "thing"), 
 pred = IriRef(
 iri = "http://www.knora.org/ontology/knora-base#isDeleted".toSmartIri, 
 propertyPathOperator = None
 ), 
 obj = XsdLiteral(
 value = "false", 
 datatype = "http://www.w3.org/2001/XMLSchema#boolean".toSmartIri
 ), 
 namedGraph = Some(IriRef(
 iri = "http://www.knora.org/explicit".toSmartIri, 
 propertyPathOperator = None
 ))
 ), 
 StatementPattern(
 subj = QueryVariable(variableName = "thing"), 
 pred = IriRef(
 iri = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type".toSmartIri, 
 propertyPathOperator = None
 ), 
 obj = IriRef(
 iri = "http://www.knora.org/ontology/0001/anything#Thing".toSmartIri, 
 propertyPathOperator = None
 ), 
 namedGraph = None
 ), 
 OptionalPattern(patterns = Vector(
 StatementPattern(
 subj = QueryVariable(variableName = "thing"), 
 pred = IriRef(
 iri = "http://www.knora.org/ontology/0001/anything#hasDate".toSmartIri, 
 propertyPathOperator = None
 ), 
 obj = QueryVariable(variableName = "date"), 
 namedGraph = None
 ), 
 StatementPattern(
 subj = QueryVariable(variableName = "date"), 
 pred = IriRef(
 iri = "http://www.knora.org/ontology/knora-base#isDeleted".toSmartIri, 
 propertyPathOperator = None
 ), 
 obj = XsdLiteral(
 value = "false", 
 datatype = "http://www.w3.org/2001/XMLSchema#boolean".toSmartIri
 ), 
 namedGraph = Some(IriRef(
 iri = "http://www.knora.org/explicit".toSmartIri, 
 propertyPathOperator = None
 ))
 )
 ))
 )

```

This is non trivial because we have to know where to add the statement. We would have to search for the statement where `?date` is an object and add it there.

I think this could take up to several days to fix, and most probably help from @benjamingeer is required.

**Comment by benjamingeer** [comment]
Why not add the statement in `AbstractPrequeryGenerator.processStatementPatternFromWhereClause`? That method is called for every statement in the input query, including the statements in an `OPTIONAL`. It takes `inputOrderBy: Seq[OrderCriterion]` as a parameter, so it can see whether the statement contains a variable that's used in the `ORDER BY` clause.

**Comment by tobiasschweizer** [comment]
Shall we give it a try next week when you are back in Basel?

**Comment by benjamingeer** [comment]
If you have a bit of time to work on it, don't feel that you have to wait for me. :) Otherwise, no problem, we can do it next week.

**Comment by tobiasschweizer** [comment]
The following query works because it contains a filter:

```
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX onto: <http://0.0.0.0:3333/ontology/0001/anything/simple/v2#>

CONSTRUCT {
  ?thing knora-api:isMainResource true .
  ?thing onto:hasDate ?date .
} WHERE {
  
  ?thing a knora-api:Resource .
  ?thing a onto:Thing .
  
  OPTIONAL {

      ?thing onto:hasDate ?date .
      onto:hasDate knora-api:objectType knora-api:Date .
     ?date a knora-api:Date .

     FILTER(?date > "GREGORIAN:2012-01-01"^^knora-api:Date)

   }

}
ORDER BY DESC(?date)
```


The prequery looks as follows:

```
 SELECT DISTINCT ?thing (GROUP_CONCAT(DISTINCT(?date); SEPARATOR='') AS ?date__Concat)
 WHERE {
 ?thing <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#Resource> .
 GRAPH <http://www.ontotext.com/explicit> {
     ?thing <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
 ?thing <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/0001/anything#Thing> .
 OPTIONAL {
 ?thing <http://www.knora.org/ontology/0001/anything#hasDate> ?date .
 GRAPH <http://www.ontotext.com/explicit> {
     ?date <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
 GRAPH <http://www.ontotext.com/explicit> {
     ?date <http://www.knora.org/ontology/knora-base#valueHasStartJDN> ?date__valueHasStartJDN .
 }
 FILTER((?date__valueHasStartJDN > "2455928"^^<http://www.w3.org/2001/XMLSchema#integer>))
 }
 }
 GROUP BY ?thing ?date__valueHasStartJDN
 ORDER BY DESC(?date__valueHasStartJDN) ASC(?thing)
 LIMIT 25
```

`?date <http://www.knora.org/ontology/knora-base#valueHasStartJDN> ?date__valueHasStartJDN` was created when transforming the filter. In that case, when processing the sort criteria the statement already exists and nothing has to be done.

**Comment by tobiasschweizer** [comment]
The proposed solution is:

simple schema: 

- move creation of statement currently handled in `NonTriplestoreSpecificGravsearchToPrequeryGenerator.getOrderBy` into `AbstractPrequeryGenerator.convertStatementForPropertyType`
- in `AbstractPrequeryGenerator.convertStatementForPropertyType`, check if:
   - the schema is the simple schema  
   - the statement's property is a value property
   - the statement's object is a variable representing a value
   - the value variable is used as a sort criterion
- if this is the case, add a statement to a collection similar to `generatedDateStatements` and add it to the returned statements 
- when processing the filter, only add additional statements if they have not been added yet   

complex schema:

- same logic as described above
