### ISSUE TITLE
How to handle Consistency Checking when the Ontology is changed

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#104]
Assuming we have an admin interface that allows for changing the ontology, how would we handle consistency checking?

> Example: A user defines an ontology using the admin interface and creates data that conforms to that ontology. He creates several instances of a resource class and now recognizes that he forgot to add a required property both to the ontology and the data. If he adds the new property to the ontology and marks it as required (e.g. cardinality = 1), the consistency of the data would be violated. Instead, he would have to add the property as an option to the resource class, add the property to all of the instances of the resource class and can then mark it as required in the ontology.

To which degree could/should this be automated?

**Comment by benjamingeer** [comment]
Let's make your example a bit more realistic:

Someone is doing something like the `incunabula` project. They make the `page` class in their ontology, but they forget to make the `book` class. They scan all the pages in 19 books and create a `page` resource for each page. Then they remember to create the `book` class, and to add `isPartOf` as a required property in `page`. I don't think Knora can automate this in any generic way, because Knora can't guess which page is in which book. The user is going to have to do what you described above. However, if the user has a list of which pages are in which book, user can write a program to automate this process using the API.

**Comment by tobiasschweizer** [comment]
My concern is that there is a contradiction between an interface that is supposed to be easy to use and to enforce data integrity at the same time (which requires the user to know what she is doing).

We could for example allow the user to add optional properties because we know that this does not effect data consistency.

**Comment by benjamingeer** [comment]
> We could for example allow the user to add optional properties because we know that this does not effect data consistency.

Nothing is currently stopping the user from adding optional properties. We don't have to do anything extra to allow this.

Or do you mean that we should forbid adding new required properties to existing resource classes? OK, but how would this work in the situation described above? The user adds the optional property, changes all the data accordingly, and then wants to change the optional property into a required property. What happens then?

There is also the opposite case: the user wants to remove a property from the ontology, but there are already a lot of resources that have that property. Currently a resource is forbidden from having properties with no cardinalities in the resource class.

What could make sense is that, when the user wants to change something in the ontology, the hypothetical ontology editor would check the data to see if any consistency checks would be violated as a result. If so, the editor would prevent the user from making the change.

**Comment by tobiasschweizer** [comment]
> What could make sense is that, when the user wants to change something in the ontology, the hypothetical ontology editor would check the data to see if any consistency checks would be violated as a result. If so, the editor would prevent the user from making the change.

Yes, exactly! 

We provide an admin interface so that the user does not have to work in the ttl-files directly, right? Consequently, we cannot expect the user to be a pro and have provide some helping tools and checks.

**Comment by subotic** [comment]
For the case of adding a required property, the admin interface could allow adding this property by automatically adding it with a default value to all resources in question. This would be somewhat equivalent to adding a new column to a table.

**Comment by benjamingeer** [comment]
> the admin interface could allow adding this property by automatically adding it with a default value to all resources in question

What would the default value be if the property is a link to another resource?

**Comment by subotic** [comment]
We could allow the user to provide the default value (e.g., link to a placeholder resource). In any case, the user would need to go into every resource and change the value to something meaningful. But then again, he could do this first, and then change this property to required afterwards.

**Comment by benjamingeer** [comment]
> We could allow the user to provide the default value (e.g., link to a placeholder resource). In any case, the user would need to go into every resource and change the value to something meaningful. But then again, he could do this first, and then change this property to required afterwards.

That makes sense to me. A similar situation exists if you want to create a loop like this:

* Resource R1 has a required property that points to resource R2
* R2 has a required property that points to R1

If the property is already required in the ontology, you have two options:

* Change the property to be optional in the ontology, create the loop, then change the property to required again.
* Use an existing placeholder resource to create R1, then create R2, then change R1 to point to R2 instead of the placeholder.

**Comment by benjamingeer** [comment]
> We could allow the user to provide the default value (e.g., link to a placeholder resource)

It just occurred to me that you could get the following problem: the required property must point to a resource of type T1, which has a required property that must point to another resource of type T2, etc., etc. You could end up having to create a whole graph of placeholder resources.
