### ISSUE TITLE
Explanation of "How does handle Knora (XML-)Files"

### ISSUE THREAD

**Issue by musicEnfanthen** [dhlab-basel/Knora#1045]
possible cases according to @tobiasschweizer : 

- TextValue  (--> StandOff)
- FileValue (--> SIPI, XSL Transformation)

It is really hard to find information about how xml files are stored with Knora in the documentation. Something seems to be here: https://docs.knora.org/paradox/03-apis/api-v1/adding-resources.html#generate-xml (but not clear which "data" is meant at all)

For new users, maybe something like "If you have an image, this happens. If you have an XML file that, and if you only have text, this will happen" could be somewhere explained without much text and the technical details (which are very detailed in the documentation), only concentrating what and especially "why" you can do this or that?

**Comment by benjamingeer** [comment]
> It is really hard to find information about how xml files are stored with Knora in the documentation. 

This is because Knora doesn't store XML files. :)

The recommended approach is to convert XML markup to standoff, which is stored as RDF. This is explained here:

https://docs.knora.org/paradox/03-apis/api-v2/xml-to-standoff-mapping.html

It is also possible to store XML files in Sipi, and to associate them with Knora resources. But then the XML files become completely opaque (not searchable) as far as Knora is concerned, so this is not recommended.

> Something seems to be here: https://docs.knora.org/paradox/03-apis/api-v1/adding-resources.html#generate-xml (but not clear which "data" is meant at all)

That's not about storing XML files, it's about bulk import of data into Knora. It's part of this section:

https://docs.knora.org/paradox/03-apis/api-v1/adding-resources.html#bulk-import

Bulk import uses XML as an input format. But it has nothing to do with storing XML.

We would welcome suggestions on how to make this clearer.

**Comment by musicEnfanthen** [comment]
Thanks for clarification. Some suggestions:

Maybe it is possible to have a section in the documentations introduction (What is Knora) where could be given a short overview what kind of "data" (file formats, other stuff) Knora is able to handle (and then link to more detailed sections with further explanations how to do it in detail). But of course the introduction shouldn't be too long only refering to the "What", "Who", Why" and "How"'s.

Concerning bulk import (https://docs.knora.org/paradox/03-apis/api-v1/adding-resources.html#bulk-import)
> In a bulk import operation, you submit an XML document to Knora, describing multiple resources to be created.

It is not clear what this XML document is? Does it look like the one shown under "Generate XML"? Does it read: `In a bulk import operation, you submit an XML **import** document to Knora **that has to be generated in advance and describes the resources that are to be created during import**.`

For the procedure, a reference to the example would be helpful.
> The procedure for using this feature is as follows [(see example below)]:

The steps in the bulk import example should correspond to the steps in the procedure.

**Comment by benjamingeer** [comment]
Also the "Generate XML" section says:

> We now convert our existing data to XML, probably by writing a custom script. The XML looks like this:

How could we make it clearer that this is an example of the XML you are supposed to generate from your data to do a bulk import?

**Comment by musicEnfanthen** [comment]
> 
> 
>  >   We now convert our existing data to XML, probably by writing a custom script. The XML looks like this:
> 
> How could we make it clearer that this is an example of the XML you are supposed to generate from your data to do a bulk import?

"The resulting XML import document could look like this / could be structured like this:"
