### ISSUE TITLE
Possibility of using StillImageRepresentation directly with v1 bulk-import

### ISSUE THREAD

**Issue by sacha-alex** [dhlab-basel/Knora#1227]
Hello,

 I just have a short question: Is it possible to create a knora-base:StillImageRepresentation resource directly within a bulk-import process using v1? Or do I have to define a subclass first (e.g.

kuno-raeber:StillImageRepresentation
		a owl:Class;
		rdfs:label "still image representation"@en, "Foto-Repräsentation"@de;
		rdfs:comment """Directory containing still images."""@en;
		rdfs:subClassOf knora-base:StillImageRepresentation.
)
and use kuno-raeber:StillImageRepresentation instead?

Thank you very much in advance.

**Comment by benjamingeer** [comment]
I think the only way to create `knora-base:StillImageRepresentation` resources using the API v1 bulk import is to use the `<file>` XML element. This is because the API v1 bulk import was designed to support files the way the rest of API v1 supports them. In the future, there will be a more flexible bulk import, but in the meantime, if the API v1 bulk import doesn't do what you need, you'll have to use Knora API v2 instead of using the bulk import.

**Comment by sacha-alex** [comment]
Thank you very much for this information. This makes it more clear.
