### ISSUE TITLE
Errors on creation of resources with huge Richtext value

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1293]
Don't really know if it is errors in my data/standoff mapping or bugs?
Could you give some help by trying to reproduce these errors:

```json
{"error":"org.knora.webapi.InconsistentTriplestoreDataException: Expected http://www.w3.org/2000/01/rdf-schema#label in assertions for a value object of type list value."}
{"error":"java.util.NoSuchElementException: key not found: http://www.knora.org/ontology/knora-base#standoffTagHasEnd"}
{"error":"java.util.NoSuchElementException: key not found: http://www.knora.org/ontology/knora-base#standoffTagHasStart"}
```
All tests are described in the README of [FailedImportTrans.zip](https://github.com/dhlab-basel/Knora/files/3047508/FailedImportTrans.zip)

**Comment by benjamingeer** [comment]
When I run `./load-onto.expect`, I get an error:

```
knora-test> load ./lumieres-lausanne_permissions.ttl into http://www.knora.org/data/permissions .
Loading data...
Malformed document: Expected ':', found ' ' [line 231]
```

It's because the file contains this line, which should be a comment but isn't:

```
Inutile compte-tenu des DOAP sur les groupes.
```

But I can still reproduce your error. Trying to figure it out now.

**Comment by gfoo** [comment]
oups sorry, didn't see that comment. thx

**Comment by benjamingeer** [comment]
This is because of the same problem as #913. The error happens because of the configured limit on the maximum number of rows in a query result in GraphDB:

https://github.com/dhlab-basel/Knora/blob/develop/webapi/scripts/graphdb-se-knora-test-repository-config.ttl.tmpl#L20

As a workaround, you can comment out the line with `owlim:query-limit-results` before creating your repository, or set "Limit query results" to 0 in the repository configuration in the GraphDB Workbench.

**Comment by benjamingeer** [comment]
You might find that it will be more efficient to split a long text into smaller pieces (e.g. chapters of a book).

**Comment by gfoo** [comment]
Fine, it works now with `owlim:query-limit-results`.
