### ISSUE TITLE
Performance consideration on API usage

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1303]
Is there an internal design in Knora encouraging a way to use the API?

For the LL web site, most of the time I have to get a resource (for example `News`) and then many related resources (for example `AdditionalResource` like images and so on).
What is the best way to get all those data?

1. get all  `News` (page of 20 resources), then for each `News` get IRIs of all `AdditionalResource` and then in parallel get all those resources. Most of the time I have about one `AdditionalResource` per `News`, so 20 http calls...

2. use gravsearch to get all  `News` and all `AdditionalResource` in one `searchextended` call.

Today I use the first solution, but when there are many related resources, and sometimes with related resources at step 2 or 3 (in terms of graph depth path), we cannot really parallelize (waiting for IRIs of next path) and load all those resources is not really efficient, without mentioning the huge number of http calls.

What do you think about these use case? Do we invest more time in gravsearch complex queries to be in any cases more efficient in terms of http call numbers but with a huge json result to read or is Knora designed for all those calls, it is, then, a model design problem if I have to get to much related resources?

n.b. : the fact is in RDF, it seems to me that we tend to _over_ model, so to create classes and related classes and so on.

**Comment by benjamingeer** [comment]
It sounds like Gravsearch might be a better option for you. Please try it and let us know if it's more efficient in your use case.

In any case, I think the first question to ask yourself is: how much data do you really need to display? It's better to get less data at first, and then get more if the user asks for more details.

Gravsearch should be an especially efficient option when the resources aren't large, or when you don't need to get all the values of each resource. Your Gravsearch query can specify which properties you're interested in. For example, you could use Gravsearch just to get certain values of each `News` resource (e.g. the title) and certain values of each `AdditionalResource`. This would help make the JSON response as small as possible. If the user wants more information about a specific news item, they can click on it, and you can then load just one complete `News` resource and/or one complete `AdditionalResource`.

In addition to the two options you described, you also have a third option: [Get a Graph of Resources](https://docs.knora.org/paradox/03-apis/api-v2/reading-and-searching-resources.html#get-a-graph-of-resources). This is an efficient way to get a whole graph of interconnected resources. It returns just the label of each resource and its links to the other resources. Then you can display the graph however you want, and if the user clicks on a resource, you can get more information about it.

> Do we invest more time in gravsearch complex queries to be in any cases more efficient in terms of http call numbers but with a huge json result to read or is Knora designed for all those calls

Knora can definitely handle a lot of HTTP requests. The bottleneck is always the triplestore. The idea of API v2 is that you only ask for what you need immediately, and you get it in small pieces. This forces you to make more HTTP requests (compared to API v1). The user clicks and gets a response quickly; they only get a small amount of data, but at least they don't have to wait a long time without seeing any response at all. Because each response only provides a small amount of data, each request can be processed quickly. Therefore we can handle more concurrency, because after the user gets a response, they'll spend at least a few seconds looking at it, and while they're looking at it, the triplestore can process a request from another user.

Gravsearch is also based on the same principle: you just get one small page of search results per request. You display the first page immediately, and when the user scrolls or clicks, you get the next page.

**Comment by benjamingeer** [comment]
> it is, then, a model design problem if I have to get to much related resources?

Knora is designed to allow you to query complex relationships between resources. This is one of the real benefits of RDF, and Gravsearch is intended for those kinds of queries. I think it's best to have a model that makes sense to you and your users, because that will make it easier for people to find what they're looking for.

> it seems to me that we tend to over model, so to create classes and related classes and so on.

I think the important thing is that model design should be driven by real use cases. I think it's best not to create abstractions unless you know you'll need them in practice. Complicated models are harder for humans to understand and work with.

**Comment by gfoo** [comment]
like #1309, this issue can be closed
