### ISSUE TITLE
Resource deletion and link property cardinality

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1425]
Let say we have this ontology : `A --hasB (owl:cardinality "1")--> B`

Is that normal that we can delete `B` and let `A` without any value for `hasB` property which breaks the cardinality rule? 

Didn't find any informations about that in the doc: https://docs.knora.org/paradox/03-apis/api-v2/editing-resources.html#deleting-a-resource

**Comment by benjamingeer** [comment]
`B` is only marked as deleted. The link between `A` and `B` is still there in the triplestore, but Knora doesn't return any information about the link via the API.

It's supposed to work like this, because `A` and `B` might be in different projects, and each project must always control its resources and be able to delete them, even if they're used by another project. I think you're right that this isn't documented anywhere, but it should be. We have thought that in the future, we could notify the owner of `A` in this case.

**Comment by gfoo** [comment]
ok, fine, was just to be sure. In my use case any way I have to check that `B` has no more incoming links before deletion.
