### ISSUE TITLE
GUI Framework Problems

### ISSUE THREAD

**Issue by lrosenth** [dhlab-basel/Knora#149]
- How to represent user data? At the moment, userdata is sent back from the server in every response and written to SALSAH.userdata. This is a problem for maintaining the `active_project` because the server does not know the active project of the user (it is always null). Can we get rid of SALSAH.userdata in the GUI? For example, we could set the user's name and the project list at login time.
- how do we handle browser refreshes when the user still has an active session? This is related to SALSAH.userdata. In fact, the session should be restored, e.g. username and project list and active project.
- change CSS: when changing the active project, the CSS should be reloaded. This must be adapted because we cannot use our CSS preprocessor anymore.

cc @milchkannen

**Comment by subotic** [comment]
> How to represent user data? At the moment, userdata is sent back from the server in every response and written to SALSAH.userdata. This is a problem for maintaining the active_project because the server does not know the active project of the user (it is always null). Can we get rid of SALSAH.userdata in the GUI? For example, we could set the user's name and the project list at login time.

I think that we need something like ``SALSAH.userdata`` in the GUI, a central place where everything about the user that he GUI needs is kept. We can certainly create it at login time and simply update it over time, e.g., store the ``active_project`` information. In Salsah 2.0 we will probably need to store it back to the server, since there the user will be able to customize a lot more things.

> how do we handle browser refreshes when the user still has an active session? This is related to SALSAH.userdata. In fact, the session should be restored, e.g. username and project list and active project.

If the ``active_project`` is only stored locally in the GUI (previous bullet point), then I don't know how we could restore it. The user will probably need to select the right project again (if it is not the first one in the list). The ``username`` and ``project list`` can be queried from the server, e.g., the default behavior, when the SALSAH page is loaded, could be to query the user API, which will then return information about the current user, identified through the session which is still active, which can then be used to populate ``SALSAH.userdata``.

>  change CSS: when changing the active project, the CSS should be reloaded. This must be adapted because we cannot use our CSS preprocessor anymore.

Maybe @milchkannen has an idea how we could do this. I'm pretty sure that this is possible.

**Comment by subotic** [comment]
@kilchenmann I think that this is all solved, or not?

**Comment by kilchenmann** [comment]
I think it's solved, yes. In salsah v2 I store the userdata locally during login. So I just need the userdata one time. I'm not sure with the project handling. At the moment we don't have project specific templates in the generic UI.
