### ISSUE TITLE
Query for all Restypes takes a very long time

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#185]
This query is very slow: <http://iml-beol.iml.unibas.ch:3333/v1/resourcetypes?vocabulary=0>

Often, I get a timeout (after 20 seconds). 

This query is cached but still it is a problem when we get a timeout the first time. 

The problem is that all existing restypes have to be queried (all vocabularies when para is set to 0).

We should have a look how to improve this query

**Comment by benjamingeer** [comment]
I talked about this with @subotic today, because he has a similar issue with caching permissions. We think it would be best to fully populate all caches when Knora starts up, instead of when data is first requested. In the ontology responder, instead of the current design, which does recursive requests and caches data a little bit at a time, we can completely load all ontologies into memory on startup. That way, once Knora has started, it will be ready to serve the first requests quickly. This would also be a simpler design.

**Comment by tobiasschweizer** [comment]
Yes, this sounds very reasonable!

When and how would you like to do this?

**Comment by benjamingeer** [comment]
Let's do it after the release.

**Comment by benjamingeer** [comment]
See also #28.
