### ISSUE TITLE
Check cardinalities of Values using Consistency Checking

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#190]
Check the cardinalities for values like they are checked for resources.

Whenever a new value is created or a new version of a value is added, the consistency checker should make sure that the SPARQL used for the updates is compliant to the ontology. e.g. that for the triples that are added to a value object the cardinalities are defined and respected.

Example:

Knora-Base:
```
###  http://www.knora.org/ontology/knora-base#IntValue

:IntValue rdf:type owl:Class ;

          rdfs:subClassOf :Value ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :valueHasInteger ;
                            owl:cardinality "1"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :valueHasString ;
                            owl:cardinality "1"^^xsd:nonNegativeInteger
                          ] ;

          rdfs:comment "Represents an integer value"@en .

``` 
SPARQL Update
```
case intValue: IntegerValueV1 => {

                ?newValue@valueIndex knora-base:valueHasInteger @intValue.ival ;
                                     knora-base:valueHasString """@intValue.toString""" .

            }
```

All the statements in a SPARQL update must conform to the cardinalities for the value type defined in the ontology, otherwise the update has to be rejected.

**Comment by benjamingeer** [comment]
To clarify: the consistency checking rules already check that the cardinalities on value classes are respected. What they don't currently do is ensure that there is some cardinality for every property of a value.

**Comment by tobiasschweizer** [comment]
I do not understand that. 

A cardinality is only checked if it is defined. But if it is not defined you can do whatever you want, e.g. assigns bogus triples to a value object?

**Comment by benjamingeer** [comment]
Each cardinality applies only to one property. All it can say is that a certain property has a minimum or maximum number of objects. Cardinalities don't provide a way to forbid someone from using a property for which there is no cardinality. There's no assumption that the list of cardinalities in a class is exhaustive. That's just how OWL cardinalities are designed. If there's no cardinality for a property, it means that the property is optional and there are no restrictions on how many objects it can have.

The current consistency rules check that every cardinality is respected, regardless of what kind of class it's in (resource, value, user, or whatever).

Since we require users to create their own resource classes, and since the GUI needs cardinalities to generate forms for creating and editing resources, I thought it would be good to ensure that there is actually a cardinality for every resource property that is used in the data. So I added a consistency rule to check this. It's a non-standard, Knora-specific extension to the semantics of OWL cardinalities. It only applies to cardinalities for properties that are accessible via the API, i.e. properties that point to values or to other resources (not to datatype properties like `lastModificationDate`). As a result, if you want to make a resource property optional, you have to give it the cardinality `owl:minCardinality 0`. This is redundant from the point of view of OWL (it's the same as not providing a cardinality), and makes sense only in Knora.

So what you're asking for is to broaden this consistency rule so it applies to properties of values, too.

**Comment by tobiasschweizer** [comment]
Yes!

I understand that from the OWL point of view, the things we are doing are totally specific to our use case and not part of the specification whatsoever. But since we have an application translating and transforming RDF triples from and to an API format, we need that control in order to ensure consistency.

And there is a lot of stuff that is not automatically ontology driven but just literally written in the SPARQL templates. When you change things in the ontology, you also have to check the SPARQL update templates. And this kind of consistency checking would help us to find inconsistencies (e.g. we removed a value property from the ontology but forgot to remove it from the update template).

**Comment by benjamingeer** [comment]
I'll see how general I can make this rule. Maybe I could try making every class in `knora-base` (`Resource`, `Value`, `User`, `Project`, etc.) a subclass of one base class, to be called something like `KnoraThing`. Then maybe I could make the rule apply to any subclass of `KnoraThing`, like this:

```
Consistency: knora_thing_prop_cardinality_any
    i <rdf:type> knora-base:KnoraThing
    i p j
    ------------------------------------
    i q j
    i <rdf:type> r
    r <owl:onProperty> q
```

**Comment by tobiasschweizer** [comment]
I am not able to understand this notation. Is this documented at Ontotext?

**Comment by tobiasschweizer** [comment]
<https://confluence.ontotext.com/display/GraphDB6/GraphDB-SE+Reasoner>

**Comment by benjamingeer** [comment]
That's the old GraphDB documentation. Start with the RST documentation on the `wip/consistency-check-optimisation` branch:

https://github.com/dhlab-basel/Knora/blob/wip/consistency-check-optimisation/docs/rst/knora-api-server/design-documentation/consistency-checking.rst

There you'll also find a link to the current GraphDB documentation:

http://graphdb.ontotext.com/documentation/standard/reasoning.html

**Comment by benjamingeer** [comment]
I've implemented this in a very minimal way on `wip/consistency-check-optimisation`: now, in addition to subproperties of `hasValue` and `hasLinkTo`, it also works for subproperties of `valueHas`. I tried to do something more general, but everything I tried was either too slow or didn't work. I think it should be possible, but we would need to contract Ontotext again to help, so maybe we can do that next year.
