### ISSUE TITLE
Can we detect unspecified members on a JSON Object when converting to Case Classes?

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#195]
Currently, when converting JSON objects to case classes using spray, additional (unspecified) members on a JSON object do not throw an error, they are just ignored. There is only an error if required members are not given or hold data of the wrong type.

However, this is error prone. If you have optional members for are case class they may be misspelled in the JSON object without the client noticing. E.g. the client wanted to submit a value for an optional member but his input is ignored because the spelling was wrong. If we could detect unspecified members on a JSON object that is meant to be converted to a case class, this kind of error would be detected.

**Comment by subotic** [comment]
Does this really matter. The API is never going to be used by a human typing in requests by hand. If the other party writes code that includes bugs, than maybe they should write some additional tests to check that they have spelled everything correctly, or not?

**Comment by subotic** [comment]
This is probably possible to implement, but would probably require to implement our own ``entity`` directive and the way how the marshalling is done. Since the inner workings are magic to me, I would need to spend a lot of time on this with no guarantee that I would ever be able to implement it ;-)

If it's very important, we can always take the raw Json, parse/check it, and afterwards create manually the object.
