### ISSUE TITLE
(settings : project) Project tools in the left side navigation panel

### ISSUE THREAD

**Issue by milchkannen** [dhlab-basel/Knora#197]
![s-ws_projects-left](https://cloud.githubusercontent.com/assets/4253580/17581240/a9bc7fd8-5fa4-11e6-9691-52e3d049e61e.jpg)
(https://projects.invisionapp.com/d/main#/console/7940249/170749741/preview)

project navigation and tools list on the left hand side in materials side navigation component (https://www.npmjs.com/package/@angular2-material/sidenav)

Which functions/tools do we need?
  - Project settings
  - Project collections
  - Project members
  - Chat
  - Project organization (only visible for project admins!)
  - more?

**Comment by jroland01** [comment]
As I understand these menus are meant for project, collection and team management ? I would argue that the left sidenav is premium, visible space in Salsah, and could therefore be put to use for more frequent / broader audience tasks (sur as e.g. faceted navigation). Settings menus could be moved (less visible) in the upper right part of the screen. What do you think ?

**Comment by jroland01** [comment]
What is the requirement for a chat application within Salsah ? Is this aimed at allowing project members to chat with each other - or is it aimed at supporting the application ? Are you intending to develop a chat system within Salsah ? I am not aware of the requirement, but I would challenge the view that a chat system is necessary within such an application, and would rather focus Salsah on asynchronous collaboration and community building, letting members use their own synchronous collaboration tools (e.g. external chat system, telephone, etc.). I see 2 problems : (1) it is probably costly to implement and would divert resources from (probably) more useful features and (2) it will clutter the interface and thus decrease the UX.

**Comment by loicjaouen** [comment]
The chat: for the requirements, I guess it is in the "team building" point of this slide:
https://projects.invisionapp.com/d/main#/console/7940249/176996498/preview

It should not be costly, it is a usual example for learning angular2. But sure, doing it right might requires a bit of thinking, even if it remains quite simple if limited to people of the project.

**Comment by jroland01** [comment]
@milchkannen Have some users somehow expressed a need for a chat function ? Do we know if some users / projects already use a "chat" system ? Furthermore, talking about team building, have we considered the possibility to post project updates, announcements e.g. through the activity feed (I am not saying there is a need for that either) ? Again, a key aspect of a good UX (if not the most important one) is to make sure functions have a clear purpose, grounded in user needs (there may be a need, but I am not sure I understand where it comes from). The risk otherwise is that users will perceive the system as "complex, with useless features", which will hamper its adoption.

**Comment by milchkannen** [comment]
Chat was just a menu item — We don't implement a chat at this time. It has a really low priority.
The main navigation menu will be in the main toolbar on the top. 
So I close this issue. It was anyway only a test to use waffle.
