### ISSUE TITLE
Library Version Conflict in SBT

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#245]
Since yesterday, I get this message when staring webapi sbt.

```
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * org.rogach:scallop_2.11:0.9.5 -> 2.0.1

```

**Comment by subotic** [comment]
This is an ongoing problem because we have too many libraries. If we want to stay current regarding the versions of libraries that we use, then there are always going to be some libraries which will be incompatible with each other. I guess the only option to solve this would be to only use libraries a few versions behind.
