### ISSUE TITLE
Salsah - the image selector is gone 

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#263]
it is not possible to add an image at the moment, instead of the file selector, there is a text selector

**Comment by benjamingeer** [comment]
You're right, thanks for this bug report. It will be fixed as part of #261.

**Comment by benjamingeer** [comment]
This was because, in pull request #252, I forgot to implement inheritance of property predicates when redesigning the ontology responder. So `knora-base:hasStillImageFileValue` didn't inherit `salsah-gui:guiElement` from `knora-base:hasFileValue`. Also, the test that should have caught this bug was incorrect. This is fixed in pull request #261.
