### ISSUE TITLE
Fix UsersResponderV1 to return None and not an exception when user not found

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#297]
When a user is not found, then the `UsersResponderV1` should return `None` and not a `NotFoundException` which is translated to into a `404` status code .

**Comment by benjamingeer** [comment]
I thought we decided that `NotFoundException` and the 404 are correct?

**Comment by benjamingeer** [comment]
In #315 I've changed `UsersResponderV1` so it doesn't use `Option` anymore, and just throws an exception if a requested user is not found. I also changed `Authenticator` to handle this change. Please let me know if this looks OK to you.

**Comment by subotic** [comment]
Yes, this is fine for now. I opened this issue before and completely forgot about it.

I say for now, because I thing that the responder should return an option, and the route should then throw an exception, if it want's. This way, we decouple the routes behaviour from the responder.

Generally speaking, I see two different use cases for a responder:

 (1) Requesting something through the route, which should return ``Not Found`` when the IRI is not correct,

(2) Internal use, by asking one responder from another for something. The response in this case should be preferably ``None``.

But to support both cases in this manner, we would need to refactor ``RouteUtil`` a bit, so that the result from the responder is returned to the calling route, and then the route needs to throw the exception or create a ``HttpResponse`` in a separate step.

**Comment by benjamingeer** [comment]
Thanks for looking at this. Currently when responders talk to each other, they can get `NotFoundException` if they ask for something (a resource, a value) that doesn't exist. This simplifies things for them, because if a responder gets a `NotFoundException` from another responder, the normal case is that the exception is just returned to the client. Since that's done automatically, there's no need for the (receiving) responder or the route to do anything about it. Currently I don't think we have any cases where a responder asks for something from another responder and it's OK if it doesn't exist.

**Comment by subotic** [comment]
> Currently I don't think we have any cases where a responder asks for something from another responder and it's OK if it doesn't exist.

Up until now ;-) But since the ``user-management2`` branch is in constant flux, this can change. I will keep you posted.

**Comment by benjamingeer** [comment]
OK :) It's not hard to change this if we need to.

**Comment by subotic** [comment]
I thought about this a bit more. If this is needed only in rare cases, then we could probably write a method that turns the result/exception into an Option. This way, we don't need to refactor the responders themselves.

Also, I had already made these changes in the ``user-management2`` branch, but your refactoring of the ``Authenticator`` is much nicer and better :-)
