### ISSUE TITLE
Switch language

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#316]
When we want to switch language from another, we get the following error after we have been asked for the confirmation:

![capture d ecran 2016-11-11 a 12 04 21](https://cloud.githubusercontent.com/assets/17294309/20213103/1790a660-a807-11e6-8106-51427fdd7408.png)

The API request answers :
```
    Request URL:http://platec.unil.ch/knora/v1/userdata
    Request Method:POST
    Status Code:404 Not Found
```

**Comment by benjamingeer** [comment]
Thanks, I'll look at this next week.

**Comment by benjamingeer** [comment]
This makes an HTTP POST to `http://localhost:3333/v1/userdata`, sending this payload:

```
{lang: "fr"}
```

That route doesn't exist (yet) in Knora. I don't understand how it's supposed to work, because it looks like the JavaScript doesn't do anything with the response, it just reloads the page (in the function `build_lang_ctrl` in `index.html`).
