### ISSUE TITLE
Diff. between documentation and knora base ontology

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#323]
- Documentation: Introduction:
     - Note: period of 1st sentence missing
    - 3rd graph: could an author in the example be represented as a person with a name instead of a literal?

- kb:ListNode:
    - kb:listNodePosition: [ontology: maxCardinality 1 ≠ documentation: cardinality 1]
    - kb:listNodeName: [ontology: maxCardinality 1 ≠ documentation: minCardinality 0]
    - kb:hasRootNode: documentation: absent

-   kb:ListValue:
    - valueHasListNode:
       - ontology: kb:objectDatatypeConstraint kb:ListNode
       -> documentation: Points to [the root] ListNode of the list or tree. -> [a] ?

- 2 properties relating an external resource to ist value: kb:hasProvider and kb:hasExtResValue.
    -> Has kb:hasProvider to be depricated?

- Docu: Links between resources:
    - Example:
        - Some colons missing in the prefix declarations
        - Could an artist in the example be represented as a person with a name instead of a literal?
        - "...link property is called [isInCollectionValue -> isInCollection], the link value property must be called [ex:isOnPageValue -> isInCollectionValue]..."
        - In the graph the predicate "isInCollection" is represented as a literal (rectangle) whereas in fact it is an instance of owl:ObjectProperty (oval).

- Permissions: in documentation explained as an xsd:string -> Can default permission annotation properties in the ontology be deprecated and in class definitions (e.g. kb:LinkObj) be redeclared as xsd:string?

- Docu: Constraints on the Types of Property Subjects and Objects:
    - kb:objectClassConstraint: "... is required [to] have this constraint ..."
    - Ontology: kb:objectDatatypeConstraint rdf:type [owl:AnnotationProperty.] to be changed to [owl:DatatypeProperty.]? (Cf. kb:subjectClassConstraint rdf:type owl:ObjectProperty.)

- note: I assume this can be removed from the ontology?: rdfs:label rdfs:subPropertyOf kb:objectCannotBeMarkedAsDeleted (rdfs:label is outside the authority of the knora BO namespace).

**Comment by benjamingeer** [comment]
Thanks! I've fixed most of these in pull request #325.

> 3rd graph: could an author in the example be represented as a person with a name instead of a literal?

I think the idea was to keep the diagram simple, especially since this section is an introduction to RDF. But you could make a pull request for this.

> Has kb:hasProvider to be depricated?

I think it was a mistake, I've removed it. The whole external resource idea needs to be clarified, but this probably won't happen until it's implemented (#293).

>        - Could an artist in the example be represented as a person with a name instead of a literal?

You could make a pull request for this.

>        - In the graph the predicate "isInCollection" is represented as a literal (rectangle) whereas in fact it is an instance of owl:ObjectProperty (oval).

The graphs are just a heuristic, so we haven't tried to make them absolutely formally consistent, but you could make a pull request for this.

> Can default permission annotation properties in the ontology be deprecated and in class definitions (e.g. kb:LinkObj) be redeclared as xsd:string?

This will happen as part of pull request #299.

>    - Ontology: kb:objectDatatypeConstraint rdf:type [owl:AnnotationProperty.] to be changed to [owl:DatatypeProperty.]? (Cf. kb:subjectClassConstraint rdf:type owl:ObjectProperty.)

I've actually never understood the purpose of `owl:AnnotationProperty`. The [documentation of owl:AnnotationProperty](https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#Annotation_Properties) is pretty vague. Would it make sense to change all our annotation properties to datatype properties?

> I assume this can be removed from the ontology?: rdfs:label rdfs:subPropertyOf kb:objectCannotBeMarkedAsDeleted (rdfs:label is outside the authority of the knora BO namespace).

We've been using this to enforce `owl:cardinality 1` on `rdfs:label` with GraphDB using the consistency rules in `KnoraRules.pie`. I'll try to get rid of it (#324).

**Comment by hanscools** [comment]
> >•Ontology: kb:objectDatatypeConstraint rdf:type [owl:AnnotationProperty.] to be changed to [owl:DatatypeProperty.]? (Cf. kb:subjectClassConstraint rdf:type owl:ObjectProperty.)
>I've actually never understood the purpose of  owl:AnnotationProperty . The documentation of owl:AnnotationProperty is pretty vague. Would it make sense to change all our annotation properties to datatype properties?
Yes, since kb:objectDatatypeConstraint and kb:resourceIcon have a datatype object (assuming the default permission properties are deprecated).
Annotations/properties are useful mainly for human understanding, e.g. rdfs:label and rdfs:comment. One can deal with them also for machine usage if finally taken into a GUI.
(Further info: http://www.w3.org/TR/owl-ref/#Annotations and
http://www.w3.org/TR/2012/REC-owl2-new-features-20121211/#Extended_Annotations)

**Comment by benjamingeer** [comment]
Reopening this issue so it can be closed when pull request #325 is merged.
