### ISSUE TITLE
Error handling in scala: catch most general error (residual) with Throwable?

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#347]
Should we use `Throwable` when handling errors with a match-case statement?

```
try {
                            strict.data.decodeString("UTF-8").parseJson
                        } catch {
                            // the Sipi response message could not be parsed correctly
                            case e: spray.json.JsonParser.ParsingException => throw SipiException(message = "JSON response returned by Sipi is not valid JSON", e = e, log = log)

                            case all => throw SipiException(message = "JSON response returned by Sipi is not valid JSON", e = all, log = log)
                        }
```

The the compiler says:
> This catches all Throwables. If this is really intended, use `case all : Throwable` to clear this warning.
[warn]                             case all => throw SipiException(message = "JSON response returned by Sipi is not valid JSON", e = all, log = log)

However, I found some warnings posts about using `Throwable`: https://www.sumologic.com/blog-code/why-you-should-never-catch-throwable-in-scala/

**Comment by tobiasschweizer** [comment]
or more generally speaking: I think we should handle all possible errors since we have to inform the user.

**Comment by benjamingeer** [comment]
`Throwable` has two subclasses: `Exception` and `Error`. The [description](http://docs.oracle.com/javase/7/docs/api/java/lang/Exception.html) of `Exception` says:

> The class Exception and its subclasses are a form of Throwable that indicates conditions that a reasonable application might want to catch.

The [description](http://docs.oracle.com/javase/7/docs/api/java/lang/Error.html) of `Error` says:

> An `Error` is a subclass of `Throwable` that indicates serious problems that a reasonable application should not try to catch.

It has subclasses like `OutOfMemoryError` and `StackOverflowError`. You won't be able to handle these, not even to inform the user, because if you can't allocate memory, you can't do anything. The most you can do is let the JVM try to shut down before the operating system kills it. So I agree with the post you linked to: you should never catch `Throwable`. That's why we catch `Exception` instead.

**Comment by tobiasschweizer** [comment]
Ok, I will use `Exception` as a residual category in my match-case statements.

Thanks for the clarification.
