### ISSUE TITLE
'knora-admin' and 'standoff' ontologies

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#378]
- Would it be considered to create an own namespace for the 'knora-admin' and 'standoff' ontologies, e.g. <http://www.knora.org/ontology/standoff#>
instead of <http://www.knora.org/ontology/knora-base#>?

- knora-base:standoffTagHasTagname: proposal to change to :standoffTagHasName

- Note: some elements in 'standoff' are not in 'knora-base', e.g.
	- knora-base:standoffTagHasXMLNamespace
	- knora-base:StandoffReferenceTag
	- knora-base:StandoffHrefTag

- knora-base:systemProperty is used in the declaration of knora-base:institutionWebsite in the 'knora-admin' ontology and for 11 properties in the 'standoff' ontology, but is not declared itself.

**Comment by benjamingeer** [comment]
`knora-base:systemProperty` was replaced by `:objectCannotBeMarkedAsDeleted`. @tobiasschweizer, could you please fix this in the standoff ontology?

**Comment by benjamingeer** [comment]
`knora-base:systemProperty` was replaced by `knora-base:objectCannotBeMarkedAsDeleted`. @subotic, could you please fix this in the `knora-admin` ontology?

**Comment by tobiasschweizer** [comment]
> Would it be considered to create an own namespace for the 'knora-admin' and 'standoff' ontologies, e.g. http://www.knora.org/ontology/standoff#
instead of http://www.knora.org/ontology/knora-base#?

Please note that standoff is still in development on the branch `StandoffUtil` (https://github.com/dhlab-basel/Knora/pull/319). There is an ontology `http://www.knora.org/ontology/standoff` for all non system relevant standoff definitions. However, system relevant definitions are kept in `knora-base`.

> knora-base:standoffTagHasTagname: proposal to change to :standoffTagHasName

`standoff.ttl` (https://github.com/dhlab-basel/Knora/blob/develop/knora-ontologies/standoff.ttl) on `develop` is deprecated and has been removed on branch `StandoffUtil`. I forgot to remove it from develop, it is a left-over of an earlier attempt to implement the desired standoff design. Sorry.

 > Note: some elements in 'standoff' are not in 'knora-base', e.g.
> knora-base:standoffTagHasXMLNamespace
> knora-base:StandoffReferenceTag
> knora-base:StandoffHrefTag

ditto

> knora-base:systemProperty is used in the declaration of knora-base:institutionWebsite in the 'knora-admin' ontology and for 11 properties in the 'standoff' ontology, but is not declared itself.

Please see Ben's comment.

**Comment by tobiasschweizer** [comment]
Please see https://github.com/dhlab-basel/Knora/blob/wip/standoffUtil/knora-ontologies/knora-base.ttl and https://github.com/dhlab-basel/Knora/blob/wip/standoffUtil/webapi/_test_data/ontologies/standoff-onto.ttl for the standoff definitions and https://github.com/dhlab-basel/Knora/blob/wip/standoffUtil/webapi/_test_data/all_data/standoff-data.ttl for the standard mapping

**Comment by tobiasschweizer** [comment]
I think I will  be able to finish the implementation of the standoff design this week or early next week. Then I will provide the necessary documentation.

**Comment by subotic** [comment]
> knora-base:systemProperty was replaced by knora-base:objectCannotBeMarkedAsDeleted. @subotic, could you please fix this in the knora-admin ontology?

Sorry, done in #379

**Comment by benjamingeer** [comment]
@hanscools is this issue still relevant? If not, let's close it.
