### ISSUE TITLE
2 KnoraRules.pie files

### ISSUE THREAD

**Issue by afa-unibas** [dhlab-basel/Knora#426]
Just a minor question: there is the following 2 Knora Rules set for consistency checking. Is there a functional difference between those?

https://github.com/dhlab-basel/Knora/blob/develop/triplestores/graphdb-se/KnoraRules.pie

https://github.com/dhlab-basel/Knora/blob/develop/webapi/scripts/KnoraRules.pie

**Comment by tobiasschweizer** [comment]
Isn't that exactly the same URL twice? :-) Maybe you wanted to compare develop to a specific commit?

**Comment by afa-unibas** [comment]
sorry for that, edited my comment above.

**Comment by benjamingeer** [comment]
They're the same file. The first one is for building a Docker image of GraphDB, as explained here:

http://www.knora.org/documentation/manual/rst/knora-api-server/development/graphdb.html?highlight=knorarules

**Comment by afa-unibas** [comment]
Ok, got that, thanks! 
(just wondered if the slight diffs have a deeper meaning)

```diff
➜  Knora git:(develop) diff webapi/scripts/KnoraRules.pie triplestores/graphdb-se/KnoraRules.pie   
311,317d310
< // Every subproperty of knora-base:resourceProperty must have a knora-base:objectClassConstraint.
< Consistency: object_class_constraint_required
<     p <rdfs:subPropertyOf> <knora-base:resourceProperty> [Constraint p != <knora-base:resourceProperty>]
<     ------------------------------------
<     p <knora-base:objectClassConstraint> c
< 
< 
351,360d343
<  * Consistency rule for owl:cardinality 1 with rdfs:label.
<  */
< Consistency: cardinality_1_not_greater_rdfs_label
<     i <rdfs:label> r [Context <onto:_cardinality_1_table>]
<     i <rdfs:label> j [Constraint j != k]
<     i <rdfs:label> k
<     ------------------------------------
< 
< 
< /*
431,440d413
< 
< 
< /*
< Consistency: standoff_parent
<     i <knora-base:standoffTagHasStartParent> j
<     i <rdf:type> t
<     ------------------------------------
<     t <knora-base:standoffParentClassConstraint> c
<     j <rdf:type> c
< */
```

**Comment by benjamingeer** [comment]
Aha, thanks for pointing that out. I'll see if we can just have one copy of this file so they don't get out of sync.

**Comment by subotic** [comment]
The only thing I can think of is to simply remove the copy inside the https://github.com/dhlab-basel/Knora/blob/develop/triplestores/graphdb-se/ folder, and require that the user makes sure to put a current copy inside the folder. The same way as with the license file.

For clarification why I put it there in the first place. Docker has a security feature, that doesn't allow adding files to an image that are not in the folder/subfolder of where the `Dockerfile` is.

**Comment by benjamingeer** [comment]
What if we leave it in `triplestores/graphdb-se` and remove it from `webapi/scripts`? The scripts in `webapi/scripts` could use the file in `triplestores/graphdb-se`.

**Comment by benjamingeer** [comment]
Actually what if we move all the GraphDB-specific scripts from `webapi/scripts` to `triplestores/graphdb-se`?

**Comment by subotic** [comment]
What if we want to add ``graphdb-free``? We would then have two separate Dockerfiles in separate directories and presumably both needing a copy ``KnoraRules.pie``.

Or as a quick fix, we could let the docker build script download this file from the ``develop`` branch?

**Comment by benjamingeer** [comment]
> What if we want to add graphdb-free? We would then have two separate Dockerfiles in separate directories and presumably both needing a copy KnoraRules.pie.

Could we make a `graphdb` directory containing `KnoraRules.pie`, with subdirectories for GraphDB SE and GraphDB Free, both of which would get the file from their parent directory?

**Comment by benjamingeer** [comment]
How about making a script that creates the Docker image, and first copies the file to the right location?

**Comment by subotic** [comment]
Certainly possible. What I don't understand is, why this is an issue? Wouldn't it be enough to simply require that the user makes sure to have a current copy inside the folder like he is required to do for the license?

Even with the script, this kind of error will still be possible, since after every ``KnoraRules.pie`` change it would be required to rebuild the docker image, and not only run the prepare scripts like it's enough for the local installation. Even for the local installation, if one doesn't know that ``KnoraRules.pie`` has changed, we run into this kind of problem.

**Comment by subotic** [comment]
Maybe we should remove the dockerfiles altogether from the Knora repository and put them in their own repository? Simply to provide an example.

For local use, since a few versions of GraphDB, it is very easy to install (a simple unzip), which is why I stopped using docker for local development.

Docker is interesting if one can automate building for deployment. Since in the Graphdb case a license is required, automation is only possible in a private setting, i.e. private repository which contains the license. In this case, the administrator will need to know what he is doing.

Regarding docker, we will never be able to provide a dockerfile that will encompass all use cases.

**Comment by benjamingeer** [comment]
The issue is just that we have two copies if KnoraRules.pie in GitHub and they keep getting out of sync.

Removing the Dockerfiles from the Knora repository sounds good to me.

**Comment by subotic** [comment]
Ok, I will remove the dockerfiles and the second copy of ``KnoraRules.pie`` from the Knora repository and update the dockerfile for GraphDB to fetch the ``KnoraRules.pie`` from the ``develop`` branch.

Is this ok?

**Comment by benjamingeer** [comment]
If you're removing the dockerfiles from the Knora repository, where will the dockerfile for GraphDB live?

**Comment by subotic** [comment]
In a separate repository. Something like dhlab-basel:docker-graphdb. Also, docker-hub could then start creating automatic builds.

**Comment by benjamingeer** [comment]
OK sounds good!
