### ISSUE TITLE
In Salsah, every resource has a "hasStandoffLinkTo" property visible

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#433]
I don't think this property is meant to be visibile for every resource in every project. 

It isn't visible in the "add resource" window, but it is always for every resource a user wants to view.

![capture d ecran 2017-02-28 a 10 22 12](https://cloud.githubusercontent.com/assets/17294309/23399552/e965f1c4-fda0-11e6-9de1-aa7ea8dfe371.png)
![capture d ecran 2017-02-28 a 10 29 46](https://cloud.githubusercontent.com/assets/17294309/23399551/e964a97c-fda0-11e6-9932-fcf3c78df9d3.png)

**Comment by benjamingeer** [comment]
It's meant to be like that, because there's a cardinality for that property on `knora-base:Resource`. Any resource could potentially contain a text value with standoff markup, which could contain links to other resources. Such links appear as direct links using the property `hasStandoffLinkTo`. This property is always created or removed automatically by the Knora API server, and users can't modify it, so it isn't visible in the "add resource" window.

**Comment by mrivoal** [comment]
Ok. I would say that this property should probably take less place within the View form because it is not necessary meaningful for the user.  But I guess users could live with it until Salsah 2.0.

**Comment by benjamingeer** [comment]
Maybe in the new GUI we could just not show properties that don't have a value.

**Comment by benjamingeer** [comment]
> And these users will need to see that those properties, even if empty, do exist to create values.

That's only true now because there is a single form for viewing and editing. But I think it would make more sense to separate these. Most users will probably only view resources and never edit them. They don't need to see properties that don't have values. There could be an "edit" button that would open the edit form, which would show all editable properties (but not this one).
