### ISSUE TITLE
Mix-up when a resource has several properties with distinct ListValues

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#441]
When there are **several lists** (either hierarchical or flat) for one resource, when the properties pointing to a `knora-base:ListValue` have a cardinality > 1, when you click the + button, you will not necessarily get the content of the right list.

In the screenshot below, it is always the same list that is looked for when you want to add more than one value.

![capture d ecran 2017-03-01 a 11 41 05](https://cloud.githubusercontent.com/assets/17294309/23456730/f74366c6-fe74-11e6-90b4-b91bd38f302f.png)

**Comment by benjamingeer** [comment]
I'm not sure I understand, and the screenshot isn't clear to me because I'm not familiar with your ontology or data. Can you give me a ZIP file containing the ontology and data (or preferably a small subset of the data)? Then I need to know what you expect to see in the GUI, not just what you actually see.

**Comment by mrivoal** [comment]
What you see here is that the list set for `Auteur de la description` or `Auteur(s) du commentaire` is always the one that Salsah is searching for when you want to add a new value for properties such as `Langue originale du commentaire`, `Langue originale de la description` et `Traducteur du verso` even if these 3 properties have their own list.

What I would expect from Salsah is for each new value attached to `Langue originale du commentaire` to search for the right list (with is a list of various languages) and not a list attached to another property (`Auteur de la description`). There is a **mix-up between all the lists used for the properties of a resource**. 

I will give you a ZIP file this afternoon.

**Comment by loicjaouen** [comment]
*mid-air collision with @mrivoal above comment*

I am pretty sure it is a salsah;
- when building the dropdown list, we populate it with the right data ("Langue" field has a dropdown list populated with "anglais")
- when we add the '+' button, the function associated now points to another list, so when we click on the '+' it builds a new drop down next to the first one but populated with "Enfant" instead of "anglais"

I will have a look and revert

**Comment by benjamingeer** [comment]
@loicjaouen If you could find where the bug is in SALSAH, that would be great, and if you could make a PR with a fix, that would be even better.

**Comment by loicjaouen** [comment]
addressed in #448
