### ISSUE TITLE
Knora Base Ontology

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#444]
- `knora-base:Annotation`: proposal to create  `knora-base:hasAnnotation` and `knora-base:hasAnnotationValue`, as inverse properties of resp. `knora-base:isAnnotationOf` and `knora-base:isAnnotationOfValue`
- typo: `knora-base:previousValue rdfs:comment "Points to the previous vers*i*on of a value"@en.`

**Comment by benjamingeer** [comment]
`hasAnnotationValue` couldn't be an inverse property of `isAnnotationOfValue`, because each of them would have to point to a `LinkValue`:

```
<annotation> knora-base:isAnnotationOf <annotated> ;
   knora-base:isAnnotationOfValue <linkvalue1> .

<linkvalue1> a knora-base:LinkValue ;
    rdf:subject <annotation> ;
    rdf:predicate knora-base:isAnnotationOf ;
    rdf:object <annotated> .

<annotated> knora-base:hasAnnotation <annotation> ;
    knora-base:hasAnnotationValue <linkvalue2> .

<linkvalue2> a knora-base:LinkValue ;
    rdf:subject <annotated> ;
    rdf:predicate knora-base:hasAnnotation ;
    rdf:object <annotation> .
```

Even if we supported OWL inference, it wouldn't do this. The Knora API server would have to generate and maintain both these reifications. That would be a lot of extra implementation work, for very little practical benefit. Inverse properties are never necessary. See:

http://graphdb.ontotext.com/documentation/standard/rules-optimisations.html#consider-avoiding-inverse-statements
