### ISSUE TITLE
Create a resource based on own ontology

### ISSUE THREAD

**Issue by sacha-alex** [dhlab-basel/Knora#545]
By using the attached Ontology we are able to create a resource, but unable to get it back
(Error Msg:"org.knora.webapi.NotFoundException: Resource http://rdfh.ch/text/wKNWyfbhT4ODm6iWahT-4Q was not found (it may have been deleted)." )

Post to create resource (JSON) via .../v1/resources:

{"restype_id":"http://www.knora.org/ontology/text#Note","label":"I_am_just_a_label","project_id":"http://data.knora.org/projects/text","properties":{}}

results in something like
{"res_id":"http://rdfh.ch/text/LJITfDecQFWNlysfblcOmQ","results":{},"status":0}

Get to verify resource:
http://localhost:3333/v1/resources/http%3A%2F%2Frdfh.ch%2Ftext%2LJITfDecQFWNlysfblcOmQ

[text-ontology-knora.ttl.zip](https://github.com/dhlab-basel/Knora/files/1085405/text-ontology-knora.ttl.zip)

**Comment by lrosenth** [comment]
@benjamingeer @sacha-alex Thanks for the issue – we'll have a look at it and keep You updated!

**Comment by loicjaouen** [comment]
@sacha-alex 
in the get request, it looks like you removed one 'F' in the '%2F' encoding '/', try:
 http://localhost:3333/v1/resources/http%3A%2F%2Frdfh.ch%2Ftext%2FLJITfDecQFWNlysfblcOmQ

**Comment by tobiasschweizer** [comment]
our preferred web service is available at https://meyerweb.com/eric/tools/dencoder/

**Comment by benjamingeer** [comment]
@sacha-alex Looks like you forgot to include the admin data for your project, which are necessary in order to create resources. Please attach this data, too. I tried just creating a simple project definition from scratch, but that's not sufficient, because default object access permissions also need to be defined.

**Comment by benjamingeer** [comment]
@sacha-alex some problems with your ontology:

You're trying to create a `:Note`. Your ontology contains two different contradictory definitions of the `:Note` class, both of which are incorrect. This is the first one:

```
:Note
	a owl:Class;
	rdfs:label "note"@en;
	rdfs:comment """Textual statement for future processing of any kind, as an object."""@en;
	rdfs:subClassOf :Text. # OR SCO knora-base:Annotation ?
```

It's defined as a subclass of `:Text`, which is a subclass of `knora-base:TextValue`. This won't work, because a resource class must be a subclass of `knora-base:Resource`. As [the documentation says](http://www.knora.org/documentation/manual/rst/knora-ontologies/knora-base.html#resources):

> All the content produced by a project (e.g. digitised primary source materials or research data) must be stored in objects that belong to subclasses of `kb:Resource`, so that the Knora API server can query and update that content.

Also, you cannot make your own subclasses of `knora-base:Value` or of any of its subclasses. The documentation [makes this clear](http://www.knora.org/documentation/manual/rst/knora-ontologies/knora-base.html#values):

> The Knora base ontology defines a set of OWL classes that are derived from `kb:Value` and represent different types of structured values found in humanities data. This set of classes may not be extended by project-specific ontologies.

Your second definition of `:Note` is as follows:

```
:Note
	a owl:Class;
	rdfs:label "note"@en;
	rdfs:comment """Text... ."""@en;
	rdfs:subClassOf :Expression.
```

This won't work either, because `:Expression` isn't a subclass of `knora-base:Resource`. It's a subclass of `work:Expression` and `cidoc:E33_Linguistic_Object`, neither of which are defined in the ontology you provided. Also, looking at the cardinalities defined on `:Expression`, I see another problem:

```
:Expression
	a owl:Class;
	rdfs:label "text expression"@en,  "Text-Expression"@de;
	rdfs:comment """Text as a human luinguistic expression."""@en;
	rdfs:subClassOf work:Expression, cidoc:E33_Linguistic_Object, [
		a owl:Restriction; owl:onProperty :hasIncipit; owl:minCardinality "0"^^xsd:nonNegativeInteger], [
		a owl:Restriction; owl:onProperty :hasExplicit; owl:minCardinality "0"^^xsd:nonNegativeInteger], [
		a owl:Restriction; owl:onProperty :hasTextRepresentation; owl:minCardinality "0"^^xsd:nonNegativeInteger], [
		a owl:Restriction; owl:onProperty :hasTextRepresentationValue; owl:minCardinality "0"^^xsd:nonNegativeInteger], [
		a owl:Restriction; owl:onProperty :hasEditedTextRepresentation; owl:minCardinality "0"^^xsd:nonNegativeInteger], [
		a owl:Restriction; owl:onProperty :hasEditedTextRepresentationValue; owl:minCardinality "0"^^xsd:nonNegativeInteger], [
		a owl:Restriction; owl:onProperty :hasDiplomaticTranscriptionRepresentation; owl:minCardinality "0"^^xsd:nonNegativeInteger], [
		a owl:Restriction; owl:onProperty :hasDiplomaticTranscriptionRepresentationValue; owl:minCardinality "0"^^xsd:nonNegativeInteger].
```

The intention here seems to be to store text as files in Sipi. This is not recommended, as I explained to @janCstoffregen in #510:

* https://github.com/dhlab-basel/Knora/issues/510#issuecomment-304223841
* https://github.com/dhlab-basel/Knora/issues/510#issuecomment-304247493

We recommend that you store text in the triplestore, in objects of type `knora-base:TextValue`. This will make your text searchable, and it supports arbitrary semantic markup, as explained in the docs:

* http://www.knora.org/documentation/manual/rst/knora-ontologies/knora-base.html#knora-base-standoff
* http://www.knora.org/documentation/manual/rst/knora-api-server/api_v1/create-a-mapping.html

Also, your ontology refers to nonexistent classes in `knora-base`:

* `knora-base:EditedTextRepresentation`
* `knora-base:DiplomaticTranscriptionRepresentation`

I also see that you're trying to refer to non-Knora ontologies such as SKOS and CIDOC. Since you're developing with Knora API version 1, there won't be any way to use these relations for now (API v1 doesn't support them). It will be possible to use them in Knora API version 2, but the procedure for doing so hasn't  yet been defined, and it might not involve `rdfs:subClassOf` or `rdfs:subPropertyOf`.

My suggestions:

* Ensure that all your resource classes are subclasses of `knora-base:Resource`.
* Ensure that each resource class is defined once and only once.
* Ensure that all the value classes you use are defined in `knora-base`, and don't make subclasses of those.
* Read the documentation to learn about how to store text with markup in a `knora-base:TextValue`. This will involve:
    * defining RDF classes to represent your markup using Knora's standoff markup functionality
    * defining an XML representation for your markup
    * defining a mapping between the RDF representation and the XML representation
* Comment out any references to non-Knora ontologies for now.

**Comment by sacha-alex** [comment]
Dear Loic, dear Tobias, dear Ben,

  thank you all for your reply and your analysis. Your suggestions helped me very much and my problem seems now resolved. Again, thank you very much for your effort and support!
