### ISSUE TITLE
Tests fail for SearchParserV2Spec.scala

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#599]
These two tests fail on `v2-search-refactor`:

- "should parse a CONSTRUCT query for an extended search *** FAILED ***"
 
- "should parse an extended search query with a FILTER containing a Boolean operator *** FAILED ***"

I think this happens because we changed  `StatementPattern` so that inference is deactivated by default (while it was enabled by default before). So if a `StatementPattern` is created without passing an arg for `StatementPattern`, it is simply the wrong way round :-)

**Comment by benjamingeer** [comment]
There were a few things broken in the test data. I fixed it, but I also made a change to `StatementPattern`. I think it doesn't make sense for `SearchParserV2` to return `StatementPattern` objects that specify a named graph, since we don't allow clients to specify named graphs. So I changed `StatementPattern` to default to a named graph of `None`. I also added a companion object with factory methods `makeExplicit` and `makeInferred`, and changed `SearchResponderV2` to use them whenever it constructs a `StatementPattern`, so it's clear whether you want inference or not.

**Comment by tobiasschweizer** [comment]
Thanks! I will continue working on extended search it tomorrow. I think we need the prequery because we need to know the order in which resources should be returned. And if we nest the Select query in the Construct query, we cannot sort the results. I has the idea that the rows returned of the Select query could have ascending integer values, but I do not think that this is possible in Sparql.

**Comment by tobiasschweizer** [comment]
Thanks for this!
