### ISSUE TITLE
Multiple Logins

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#81]
When I call http://localhost:3333/v1/session?username=root&password=test&login=1 multiple times, I always get a new session id.

Shouldn't the server recognize that with the second request a cookie is sent that already contains a valid session id (the one that was returned with the first request) and send this back instead of creating another session?

**Comment by subotic** [comment]
It depends. I tried to design the session API endpoint in a resource centric way. If you look at this request as an operation for creating a new session, then the behavior is correct. This will be clearer if you look at ```AuthenticationRouteV1```. Adding a ```login``` or ```logout``` parameter to a ```HTTP GET``` request has the same effect as simply doing a ```HTTP POST``` or a ```HTTP DELETE``` request. Maybe instead of ```login / logout``` it should be better called ```create / delete```.

**Comment by tobiasschweizer** [comment]
But wouldn't it make sense to check for an existing session before creating another one?

What's the point of having more than one active session for one client?

**Comment by subotic** [comment]
Yes, maybe. This is just how I implemented it. There shouldn't be multiple active sessions. When a new session is created by the client, then the old one should be deleted from the server (this is missing at the moment).

On the other hand, not deleting the old session is maybe a good thing. Namely, another question just popped in my mind. Are we going to allow a user to be "logged-in" from multiple locations? If so, then we could simply leave it as it is, so that each location can have it's own session id, or change it so that all locations have the same session id.
