### ISSUE TITLE
Define ARK IDs

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#844]
# ARK existing server

here is an ARK ID:

[`http://`NMAH`/`]`ark:/`NAAN`/`Name[Qualifier]

where:

- NMAH, Name Mapping Authority Host, for us is: `ark.dasch.swiss`
- NAAN, Name Assigning Authority Number, for us is: `72163`

resulting in this ark-id for a resource in salsah v1:

`http://ark.dasch.swiss/ark:/72163/0801-31ec6eab334-c.201852`

which is translated into:

`http://data.dasch.swiss/resources/3491?citdate=201852`

In the ark-id, the string `0801-31ec6eab334-c.201852` means:
- `0801` is the project id, and that it is mapped to `http://data.dasch.swiss/resources/`
- the resource code `31ec6eab334` is mapped to `3491`
- and append the transformed `c.201852` to `?citdate=201852`

# Knora and ARK

So an ark-id could be:
`http://ark.dasch.swiss/ark:/72163/0105--AU-w879ReyDWm6wpwZnAw-c.201852`

Where:
- project `0105` would be mapped in the ark mapping server to `http://knora-demo.unil.ch/v1/resources/http://rdfh.ch/0105/drawings-gods/`
- `-AU-w879ReyDWm6wpwZnAw` is the resource IRI and would remain the same

So it would end up as the knora call:
- `http://knora-demo.unil.ch/v1/resources/http://rdfh.ch/0105/drawings-gods/-AU-w879ReyDWm6wpwZnAw`

# Project specific web app

Registering a project specific web app, we could set the project mapping to `http://ddd.unil.ch/permalink/` and the same `http://knora-demo.unil.ch/v1/resources/http://rdfh.ch/0105/drawings-gods/-AU-w879ReyDWm6wpwZnAw` would redirects to `http://ddd.unil.ch/permalink/-AU-w879ReyDWm6wpwZnAw`

**Comment by loicjaouen** [comment]
@lrosenth , could you review this specs and spread the knowledge of how it works now?

**Comment by gfoo** [comment]
Any news about the ark feature in Knora ? 
In our app we want to provide an url to a resource using of course a long-term ark url : 
- is there a general rule to generate in our app the ark URL of a resource or is there a way in the Knora API to get the ark URL of a resource ?
- and what is the final route of an ark, a running Salsah somewhere  ? Can we configure it to route to a  
 running Salsah here in Lausanne ?

thanks.

**Comment by benjamingeer** [comment]
ARK URLs need to support timestamps, so you can cite a resource as it was at a specific point in time in the past (#1115).

**Comment by lrosenth** [comment]
They do :-)

Von meinem iPhone gesendet

Am 07.12.2018 um 17:32 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


ARK URLs need to support timestamps, so you can cite a resource as it was at a specific point in time in the past (#1115<https://github.com/dhlab-basel/Knora/issues/1115>).

**Comment by benjamingeer** [comment]
@lrosenth Could you write a specification for Knora's ARK IDs? (Or could we do this together sometime soon?) Also, can we put your ARK server code on GitHub?

**Comment by lrosenth** [comment]
a old-salsah-ark-PID looks like this:

```http://ark.dasch.swiss/ark:/72163/0801-fc13aad606-a.20181207```

It has the following parts:

- ```http://ark.dasch.swiss```: This is the URL of the resolver
- ```ark:/72163```: This is the assigned number for DaSCH
- ```0801```: This is the Knora project number as hex
- ```fc13aad606```: This is the ID calculated from the old salsah resource id
- ```a```: This is a checksum calculated as below
- ```20181207```: This is the date the reference is being made (added by the GUI using tzhe current date.

The ID is calculated as follows

```php
$tmp = bcmul('982451653', (string) (intval($id) + 1), 0); // use big int multiplication
$tmp = bcdechex($tmp); // convert result to hex
```

The checksum is the Luhn-Checksum. The full PHP code is as follows. For the Checksum see zthe Luhn class.

The basic feature is that the the resource_id can be determined by the ARK-id, since the multiplication is done with a prime number (982451653 is  prime) and therefore the result is deterministic and reversible.

I suggest that the new ARK's for Knora should follow the same principles. We have to determine how we are transporting the old salsah-ARKs to Knora! It must be possible to find the resource using the ARK id :-)

[ark_inc.php.zip](https://github.com/dhlab-basel/Knora/files/2658172/ark_inc.php.zip)

**Comment by benjamingeer** [comment]
Hmm, but ideally, when a project is exported from the old SALSAH into Knora, it should keep the same ARK URLs, which would now point to Knora.

Each Knora resource IRI already contains a unique random ID, which we could use as the ID in the ARK URL.

If we implement #176 (allow projects to specify custom IRIs for new resources), you could specify the IRI of each resource that you create using the bulk import, instead of getting a random ID generated for each resource.

Then the same resources could have the same ARK URLs in the old SALSAH and in Knora.

When we import an old SALSAH project into Knora, we would just have to tell the ARK server to resolve that project's URLs using the Knora server instead of the old SALSAH server.

Does that make sense?

**Comment by lrosenth** [comment]
yes, I think this would make perfectly sense!

**Comment by benjamingeer** [comment]
A date in the format `20181207` is ambiguous because it doesn't have a timezone, and it wouldn't be precise enough for a citation if the resource was modified more than once per day. Knora uses `xsd:dateTimeStamp` (with the UTC timezone) for timestamps (http://www.datypic.com/sc/xsd11/t-xsd_dateTimeStamp.html). Could we use that format, like this?

```
http://ark.dasch.swiss/ark:/72163/0801-fc13aad606-a.2018-12-07T00:00:00Z
```

**Comment by lrosenth** [comment]
Hi Ben,

good point! I think we can do this without problem since the date as actually not part of the core ARK-identifier, but an option which has to be dynamically resolvded... I have to see how to get thios date format in JavaScript ;-)


Lukas

Am 14.01.2019 um 12:10 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


A date in the format 20181207 is ambiguous because it doesn't have a timezone, and it wouldn't be precise enough for a citation if the resource was modified more than once per day. Knora uses xsd:dateTimeStamp (with the UTC timezone) for timestamps (http://www.datypic.com/sc/xsd11/t-xsd_dateTimeStamp.html). Could we use that format, like this?

http://ark.dasch.swiss/ark:/72163/0801-fc13aad606-a.2018-12-07T00:00:00Z

**Comment by benjamingeer** [comment]
Thanks! In JavaScript you can use [Date.toISOString()](https://www.w3schools.com/jsref/jsref_toisostring.asp).

**Comment by benjamingeer** [comment]
Another problem: the Luhn checksum in the PHP code only works with hexadecimal numbers, and it ignores case. But Knora's randomly-generated resource IDs use Base64 encoding, which includes the characters `a-z`, `A-Z`, `_`, and `-`, and case is significant. So we need a different checksum algorithm that will work with both kinds of resource IDs.

**Comment by lrosenth** [comment]
I'mjust thinking, do we need the checksum (we could ignore it possibly). The idea behind it was to have the possibility in the GUI to check the correct entry of the ARK-id – but since most ID's will be entered by copy/patse I'm not sure if we need this feature... What do You thing??

Lukas

Am 14.01.2019 um 12:47 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


Another problem: the Luhn checksum in the PHP code only works with hexadecimal numbers, and it ignores case. But Knora's randomly-generated resource IDs use Base64 encoding, which includes the characters a-z, A-Z, _, and -, and case is significant. So we need a different checksum algorithm that will work with both kinds of resource IDs.

**Comment by benjamingeer** [comment]
When someone copies and pastes a URL, it's easy to leave out the last character by accident (which could be the last character of the resource ID, if the timestamp was not provided), so it would be nice to be able to check that the URL is correct. But there's no way we can prevent someone incorrectly copying and pasting an ARK URL from Knora into a Word document (e.g. because they're writing a journal article). The only difference is that without the checksum, they will get either:

1. an HTTP 404 error from Knora, if the incorrect ID doesn't correspond to any resource (which will probably be the case)
2. the wrong resource, if they're really unlucky and there is a resource with that ID.

(1) seems fine to me, but (2) would be annoying. Is this a good enough reason to include the checksum?

I was actually working on a checksum implementation for the Base64 alphabet, based on the check digit used in the [Code 128](https://en.wikipedia.org/wiki/Code_128#Check_digit_calculation) barcode standard...

**Comment by benjamingeer** [comment]
Although, if we're just worried about someone forgetting to copy the last character of the URL, we could use any character instead of a checksum.

**Comment by lrosenth** [comment]
Hi Ben,


that's a perfect reasoning... Your idea sounds good!! Have You time later for a short skype? I'm still at home and not feeling so well :-|

Lukas

Am 14.01.2019 um 13:48 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


When someone copies and pastes a URL, it's easy to leave out the last character by accident (which could be the last character of the resource ID, if the timestamp was not provided), so it would be nice to be able to check that the URL is correct. But there's no way we can prevent someone incorrectly copying and pasting an ARK URL from Knora into a Word document (e.g. because they're writing a journal article). The only difference is that without the checksum, they will get either:

  1.  an HTTP 404 error from Knora, if the incorrect ID doesn't correspond to any resource (which will probably be the case)
  2.  the wrong resource, if they're really unlucky and there is a resource with that ID.

(1) seems fine to me, but (2) would be annoying. Is this a good enough reason to include the checksum?

I was actually working on a checksum implementation for the Base64 alphabet, based on the check digit used in the Code 128<https://en.wikipedia.org/wiki/Code_128#Check_digit_calculation> barcode standard...

**Comment by benjamingeer** [comment]
Yes, I'm here, please call on Skype and we can decide what to do.

**Comment by benjamingeer** [comment]
How about if we do it like this:

* The Knora API returns the ARK URL along with the rest of the resource metadata.
* The ARK resolver validates the checksum.

Then the generation of the ARK URL only needs to be implemented in Knora, and the checksum validation only needs to be implemented in the ARK resolver.

**Comment by lrosenth** [comment]
Good point!!

Am 14.01.2019 um 16:53 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


How about if we do it like this:

  *   The Knora API returns the ARK URL along with the rest of the resource metadata.
  *   The ARK resolver validates the checksum.

Then the generation of the ARK URL only needs to be implemented in Knora, and the checksum validation only needs to be implemented in the ARK resolver.

**Comment by benjamingeer** [comment]
I would also like to add a version number for our ARK URL format, in case we decide to change the format later, would that be OK? Example with version number 1:

```
http://ark.dasch.swiss/ark:/72163/1-0801-fc13aad606-a.2018-12-07T00:00:00Z
```

**Comment by lrosenth** [comment]
Perfect!1

Sent from my iPad

On 15 Jan 2019, at 08:49, Benjamin Geer <notifications@github.com<mailto:notifications@github.com>> wrote:


I would also like to add a version number for our ARK URL format, in case we decide to change the format later, would that be OK? Example with version number 1:

http://ark.dasch.swiss/ark:/72163/1-0801-fc13aad606-a.2018-12-07T00:00:00Z

**Comment by benjamingeer** [comment]
OK, another problem: since Base64 contains the `-` character, we can't use it as a delimiter. How about a dot instead?

```
http://ark.dasch.swiss/ark:/72163/1.0001.cmfk1DMHRBiR4-_6HXpEFA.T.2018-12-07T00:00:00Z
```

**Comment by benjamingeer** [comment]
About delimiters: [the draft ARK RFC](https://tools.ietf.org/html/draft-kunze-ark-17#section-2.5) says that the optional "qualifer" after the object name has a specific meaning:

```
   If the ARK contains an internal slash after the NAAN, the piece to
   its left indicates a containing object.  For example, publishing an
   ARK of the form,

                       ark:/12025/654/xz/321

   is equivalent to publishing three ARKs,

                       ark:/12025/654/xz/321
                       ark:/12025/654/xz
                       ark:/12025/654

   together with a declaration that the first object is contained in the
   second object, and that the second object is contained in the third.
```

So I think this would make sense:

```
http://ark.dasch.swiss/ark:/72163/1.0001.cmfk1DMHRBiR4-_6HXpEFAT/2018-12-07T00:00:00Z
```

This way, `1.0001.cmfk1DMHRBiR4-_6HXpEFAT` is the object name, containing:

* `1`: the Knora ARK version
* `0001`: the project ID
* `cmfk1DMHRBiR4-_6HXpEFA`: the resource ID
* `T`: the check digit (no need for a delimiter here, because it needs to be appended to be checked anyway)
* `2018-12-07T00:00:00Z`: the timestamp

I think it makes sense for the timestamp to be a qualifier, because it really is a sub-object, and the base object `http://ark.dasch.swiss/ark:/72163/1.0001.cmfk1DMHRBiR4-_6HXpEFAT` also exists.

**Comment by benjamingeer** [comment]
Actually no, because the `.` and `-` characters are also reserved in ARK. In short:

* `/` is for object hierarchy
* `.` is for object variants
* `-` is ignored

Thinking about this some more, we could actually consider the project ID as an object, too, pointing to the project as a whole (e.g. its home page).

The timestamp is perhaps more of a variant.

Even the ARK version number is a sort of object, which could just be a page explaining the Knora ARK syntax.

So the only remaining problem is `-`, which has to be replaced by some other character.

**Comment by benjamingeer** [comment]
Simpler and more standard than escaping `-`: use [Base32 encoding](https://en.wikipedia.org/wiki/Base32) for the resource ID.

Also, in the timestamp, we need to omit `:`, which is optional in ISO 8601 and would otherwise need to be URL-encoded.

**Comment by benjamingeer** [comment]
OK, I've implemented something in #1161. Any feedback would be welcome.

**Comment by loicjaouen** [comment]
if I get it right:

```
http://ark.dasch.swiss/ark:/72163/1.0001.cmfk1DMHRBiR4-_6HXpEFAT/2018-12-07T00:00:00Z
ark-base-url               /dasch/v.proj  . base64(IRI)        T/timestamp      
```
with `v` being DaSCH's version of ark naming schema 

and `/` is for object hierarchy and `. ` is for object variants.

I would have expected something like: an object is part of a project which is part of DaSCH, so:

- ark-base-url`/`dasch`.`v`/`proj`/`base64(IRI)`T.`timestamp

instead of:

- ark-base-url`/`dasch`/`v`.`proj`.`base64(IRI)`T.`timestamp

I guess that the `/`dasch`/` is mandatory by the ark general naming convention.

Hmmm.... I guess that what we are looking at as `object` is not an object that we store in the database but it's name?

**Comment by benjamingeer** [comment]
@loicjaouen Also please note that the delimiters are a bit different from what you wrote above:

https://github.com/dhlab-basel/Knora/blob/8b5591cd1e8c49b4e30c3a092a9d2b0ffd0a7eb7/docs/src/paradox/03-apis/api-v2/resource-permalinks.md

**Comment by loicjaouen** [comment]
wonderful,it makes perfect sense then

**Comment by loicjaouen** [comment]
can I bring a use case?

It is not linked to how knora should forge the ark id but still linked to the naming schema.

Could we use the ark id for both:
- the *data preservation access* (knora/salsah for now and whatever will the technical solution be at the time of access)
- a *project dissemination* site (`lumieres.unil.ch` or `beol.dasch.swiss`?)

Where the end part of the ark could be `.t`*timestamp* and/or `.a` for an alternative viewer.

That would imply that the ark dereferencing server would have two entries per project (*data preservation access* and *project dissemination*) and would use the latter if `.a` is appended to the id. Also knora should learn to ignore it.

**Comment by loicjaouen** [comment]
it boils down to:
- adding a specifier to the trailing optional parameters and
- for an ark id viewer, ignoring the optional parameters that it doesn't know

**Comment by benjamingeer** [comment]
So as long as the object is available at `lumieres.unil.ch`, the redirect server would redirect you to that host. If someday `lumieres.unil.ch` is no longer available, we can change the configuration for that project to use some other host.

**Comment by loicjaouen** [comment]
that makes sense, thanks @benjamingeer
