### ISSUE TITLE
What permissions should a LinkValue for a standoff link have?

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#88]
When we create a new `LinkValue` for a standoff link to a resource, what permissions should the `LinkValue` have? Currently it gets the same permissions as the `TextValue` containing the standoff. But that doesn't really make sense. Resource R1 could have 3 different properties, each of which points to a `TextValue` containing a link to the same resource R2. This would generate one direct link between the resources (via the property `hasStandoffLinkTo`), and one one `LinkValue` for that link, with a reference count of 3. If each of those `TextValue` objects has different permissions, what permissions should the `LinkValue` have?

cc @subotic @tobiasschweizer

**Comment by subotic** [comment]
For me, the `LinkValue` represents a connection between two resources (`R1`, `R2`), brought upon by a property value (`V`). From my understanding, the `LinkValue` is not created directly by the user, but by the system as a consequence of something the user did. In this case, the user linking to a resource from inside the `TextValue`'s (`V1`, `V2`, `V3`). So, the only question I see here is what `ViewPermission` this `LinkValue` is going to have, since allowing someone to delete or modify it doesn't make much sense to me (he should modify/delete the `TextValue` directly, which in turn will trigger a change in the `LinkValue`).

As for the `ViewPermission`, I would say the lowest of the bunch. If I have the permission to see value `V1`, but not `V2` or `V3`, then I should still be able to see the `LinkValue`. But then if `V1` is changed to not point to resource `R2` anymore, then the lowest permission of `V2` or `V3` should be taken, which is probably a pain to implement. Or maybe I have misunderstood the workings of `LinkValue` completely, then just ignore this comment :-)

**Comment by subotic** [comment]
Ah, and if the user does not have the `ViewPermission` for `R2`, then he shouldn't be allowed to see the link, even if he has the right to see `V1` and the `LinkValue`. Dose this make sense? This goes hand in hand with #89 .

**Comment by benjamingeer** [comment]
> From my understanding, the `LinkValue` is not created directly by the user, but by the system as a consequence of something the user did. In this case, the user linking to a resource from inside the `TextValue`'s (`V1`, `V2`, `V3`). So, the only question I see here is what `ViewPermission` this `LinkValue` is going to have, since allowing someone to delete or modify it doesn't make much sense to me

That's right.

> As for the `ViewPermission`, I would say the lowest of the bunch. If I have the permission to see value `V1`, but not `V2` or `V3`, then I should still be able to see the `LinkValue`.

That would be the highest permission, right? Your permission on `V1` is higher than your permission on `V2`, so we pick the permission on `V1`.

This would make sense, and maybe it's what users would expect. It probably wouldn't be a huge pain to implement, but it's not trivial, because the `LinkValue` doesn't actually know about `V1`, `V2`, or `V3`. Each time any of those text values was changed, we'd have to find all the text values in the same resource that have standoff links to the same target, calculate the user's permissions on all those text values, and pick the highest permission. I guess we could write one SPARQL query that would find all the relevant text values (except the one we're changing) and return all their permissions, then the rest would be pretty straightforward.

A simpler solution could be that the `LinkValue` just gets the same permissions as the resource that contains it, but I don't know if that's good enough.

**Comment by benjamingeer** [comment]
> Ah, and if the user does not have the `ViewPermission` for `R2`, then he shouldn't be allowed to see the link, even if he has the right to see `V1` and the `LinkValue`. Dose this make sense?

I think it makes sense. Currently the resources responder does this for outgoing links but not for incoming links.

**Comment by subotic** [comment]
>> As for the `ViewPermission`, I would say the lowest of the bunch. If I have the permission to see value `V1`, but not `V2` or `V3`, then I should still be able to see the `LinkValue`.

>That would be the highest permission, right? Your permission on `V1` is higher than your permission on `V2`, so we pick the permission on `V1`.

Actually I meant it the other way around :-) The permission on `V1` is the lowest one as in least restrictive. As an example, the permission on `V1` allows the user only to see it and the permissions on `V2` and `V3` only allow only the creator of those links to see them. Now I don't know if the link itself inside the `TextValue` can have permissions, or if the permissions for all links inside a `TextValue` are the same as in the `TextValue` itself.

>A simpler solution could be that the `LinkValue` just gets the same permissions as the resource that contains it, but I don't know if that's good enough.

Yes, that's also something that crossed my mind. If the user has `ViewPermission` for both `R1` and `R2`, then he would simply see the link. Albeit he wouldn't know why the link is there, if he, as an example, does not have the necessary permission to see `V1`, `V2`, or `V3`.

Just to make sure (since the user has the choice of setting permissions), if a user does not have `ViewPermission` for `R1` then he shouldn't be able to be given `ViewPermission` or higher to a value attached to `R1`.

**Comment by benjamingeer** [comment]
> The permission on `V1` is the lowest one as in least restrictive.

OK. In the Knora code, there's a hierarchy of permissions, identified by integers, and the higher permissions (the ones with higher numbers) allow you to do more things with the object.

> if a user does not have `ViewPermission` for `R1` then he shouldn't be able to be given `ViewPermission` or higher to a value attached to `R1`.

A while ago I asked Lukas about this, and he decided that permissions on values should be independent of permissions on resources. So I added this sentence to `knora-base.tex` (section 5.2):

> Having view permission on a resource only affects the user’s ability to view information about the resource other than its values. To view a value, she must have view permission on the value itself.

This simplifies permission checking, because if the user is just asking to view a value, we only need to check view permission on the value, not on the resource.

**Comment by benjamingeer** [comment]
> Now I don't know if the link itself inside the `TextValue` can have permissions, or if the permissions for all links inside a `TextValue` are the same as in the `TextValue` itself.

Standoff nodes don't have permissions. There are only the permissions on the `TextValue` itself.

**Comment by subotic** [comment]
>> if a user does not have `ViewPermission` for `R1` then he shouldn't be able to be given `ViewPermission` or higher to a value attached to `R1`.

>A while ago I asked Lukas about this, and he decided that permissions on values should be independent of permissions on resources. So I added this sentence to `knora-base.tex` (section 5.2):

>> Having view permission on a resource only affects the user’s ability to view information about the resource other than its values. To view a value, she must have view permission on the value itself.

>This simplifies permission checking, because if the user is just asking to view a value, we only need to check view permission on the value, not on the resource.

What I meant is that Knora should not allow giving the `ViewPermission` to the value in the first place. I don't know what the use case would be. It's just something that popped up in my mind, since I'm thinking allot about permissions lately. The analogy (maybe) would be to give someone access to a file on a filesystem without giving him access to the folder. How would the person get to the file? Yes, he could be given the IRI of the value, but what for? Anyway, if Lukas wants it then let's give it to him :-)

**Comment by subotic** [comment]
>> Now I don't know if the link itself inside the `TextValue` can have permissions, or if the permissions for all links inside a `TextValue` are the same as in the `TextValue` itself.

>Standoff nodes don't have permissions. There are only the permissions on the `TextValue` itself.

Thanks. Good news :-) The permissions are complex enough, as it is.

**Comment by benjamingeer** [comment]
> The analogy (maybe) would be to give someone access to a file on a filesystem without giving him access to the folder. How would the person get to the file? Yes, he could be given the IRI of the value, but what for? Anyway, if Lukas wants it then let's give it to him :-)

There are already various other nonsensical things that users can do with permissions in Knora if they really want to. The question is how much effort we should expend to prevent these things. In this case, since we only grant permissions to groups, we would have to check whether there are any groups that have view permission on the resource but not on the value. This would be non-trivial, because you can get view permission implicitly by having some higher permission. Maybe we could think about implementing this later as part of a more general sanity check function (after consistency checking works).

**Comment by benjamingeer** [comment]
@tobiasschweizer what do you think?

**Comment by benjamingeer** [comment]
@subotic could you please look at this again and see what you think, given the new permissions design?

**Comment by benjamingeer** [comment]
Ivan suggests: the `LinkValue` should have no permissions, because the API doesn't provide any way to change those permissions, and probably shouldn't, because link values for standoff resource references are not supposed to be manipulated directly by the user. If you have permission to see the source and target resources, you should have permission to see the link.

**Comment by tobiasschweizer** [comment]
Just to summarise:
- for conventional linkValues (a resource has a linking property that points to another resource), reference count is 1 at max (set to 0 when the link was deleted). So there is exactly one owner and we do not have any problem.
- for standoff links however, there might be several links from the same source resource to the same target resource, depending on the amount of TextValues that have standoff links. And these TextValues could have been created by different users. 

In the second case, by looking at the TextValue we know who the owner is/are and can determine if someone has the right to delete or change the TextValue including links. The permissions on a LinkValue could be derived from that. 

**But in the first case the owner would have to be stored in the LinkValue, otherwise we do not know about a user's permissions on it.**

**Comment by benjamingeer** [comment]
> In the second case, by looking at the TextValue we know who the owner is/are and can determine if someone has the right to delete or change the TextValue including links. The permissions on a LinkValue could be derived from that.

We can't do that, because a single `LinkValue` can represent standoff links originating in several different text values. The reference count of a `LinkValue` is the number of text values that have standoff links to the same target resource.

> But in the first case the owner would have to be stored in the LinkValue, otherwise we do not know about a user's permissions on it.

Yes, but the question in this issue is about the second case.

Here's what the code currently does:

1. When the resources responder queries outgoing links (in the `queryResults2PropertyV1s` method), the user must have permission to see the source resource, the target resource, and the `LinkValue`.
2. When the resources responder queries incoming links (in the `getFullResponseV1` method), the user only needs permission to see the source resource and the target resource, not the `LinkValue`. **This should be made consistent with (1).**
3. When we create a normal (non-standoff) link, the `LinkValue` gets permissions like any value.
4. When we create a standoff link, the `LinkValue` (or the new version of the `LinkValue`) gets the permissions from whatever `TextValue` has been added or changed. **This is obviously wrong.**

So I think we can do this:

* Don't attach any owner, project, or permissions to link values for standoff.
* When querying links (whether outgoing or incoming), ensure that the user has permission to see the source resource and the target resource. Also ensure that the user has permission to see the `LinkValue`, **unless** the link property is `hasStandoffLinkTo`. We're justified in making this property a special case because it's system-maintained as a side effect of standoff.

**Comment by benjamingeer** [comment]
If link values for standoff didn't have owners, we would have to make the owner optional on `LinkValue`, which would limit consistency checking. Instead, we can make a system user, who is the owner of all link values for standoff.
