### ISSUE TITLE
xsd cardinality checks for richtextValues in different languages

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#929]
well current implementation of language option for richTextValues kind of shadows the defined cardinalities. 

For example: 
Originally we had set max cardinality for a person's birthplace to be= 1:

![screen shot 2018-07-10 at 11 11 31](https://user-images.githubusercontent.com/8567642/42500631-19d3f8e2-8432-11e8-96b2-fccf8c822420.png)

but with current implementation of language option a person can have multiple birthplace properties written in different languages(see below for xml element), which is not accepted by xsd based on cardinality defined for "hasBirthPlace" property in ontology. 

![screen shot 2018-07-10 at 11 11 16](https://user-images.githubusercontent.com/8567642/42500647-241dbc66-8432-11e8-85b0-783e8e574807.png)

possible solutions would be: 
1. change cardinalities in ontology. (This would not be the optimal way because just by looking at ontology, a person should just have one birthplace)
2. add a check to xsd, that if the maxCardinality was one but more properties were provided, it should check that language attribute of these properties are different. In this example: If there are more than one "hasBirthPlace" properties defined in xml, their lang attribute should not be the same. 

@benjamingeer what do you think?

**Comment by benjamingeer** [comment]
The problem is not just the XSD. The cardinalities have to be respected in the triplestore. The GraphDB consistency checking rules would have to be changed to take this into account, which would be a lot of work because the whole optimisation strategy would have to be redone.

If it bothers you to change the cardinality, I suggest making the birthplace into a resource class. Then you can have `maxCardinality 1` on a link property pointing to a birthplace resource.

**Comment by SepidehAlassi** [comment]
@benjamingeer I am aware that it is not only xml import and xsd problem and that it can cause a lot of headache. 
Then lets live with changing cardinalities for now, but keep in mind maybe one day if we had time, we take care of this :-P

**Comment by benjamingeer** [comment]
Also:

* Maybe there are cases where someone would want `maxCardinality 1` to really limit the number of values to 1, regardless of language.
* If we change the meaning of `maxCardinality 1` by introducing an exception to the rule, it makes it more difficult to switch to some other constraint system like SHACL later.

I agree that the ability to have different "equivalent" values in different languages doesn't really fit with the concept of cardinalities. But I think the problem is inherent in the OWL cardinality language. We could change the design of `knora-base` by adding another level below `TextValue`, which would hold texts in different languages. But that would make everything more complicated.

I think that by creating a `Birthplace` resource class (with a property like `birthplaceName`), you can solve the problem pretty neatly, without requiring a major redesign of anything.

**Comment by benjamingeer** [comment]
Also, perhaps using a resource class instead of a text value would have other advantages. For example, you could use a `City` resource class with a GeoNames ID. This would make the data less redundant. And then a Gravsearch query could find people who were born in a particular city by supplying its GeoNames ID.

**Comment by SepidehAlassi** [comment]
yes, resource class for places instead of text value makes sense however it also mean lots of adjusting has to be done in already existing xml files of BEOL project which are mostly manually modified. :-/ right now I really don't have time to write a script to take care of it. maybe later!
