### ISSUE TITLE
trouble with xml-checker and/or consistency-checker during bulk import

### ISSUE THREAD

**Issue by sacha-alex** [dhlab-basel/Knora#978]
@benjamingeer @lrosenth @ezbinden 

Dear Ben, dear Lukas, dear Erwin,

  as discussed at the latest DaSCH-Leitungstreffen last Tuesday, I want to describe an important issue that we face in Knora.
Since you might know, we are dealing with several ontologies in parallel and using inheritance heavily. For example, please take a look at the following (real) example: 

  When someone is dealing with a kuno-raeber:Poem resource, it is inherited like this:

                 ----------------------------------------> kuno-raeber:Poem <------------------------------------
                |                                                                                                |
    kuno-raeber:Text                                                                                         litera:Poem
    (hasAuthor card=1)                                                                                           ^
                ^                                                                                                |
                |                                                                                         litera:Expression
                |                                                                                                ^
                |                                                                                                |
                 ---------------------------------------   text:Expression    ----------------------------------- 
                                                        (hasAuthor minCard=0)
                                                                  ^
                                                                  |
                                     ---------------------------------------------------------
                                    |                                                         |
                                text:Text                                            document:Expression
                                    ^                                                         ^
                                    |                                                         |
                language:HumanNaturalLanguageExpression                               document:Document
                                    ^                                                         ^
                                    |                                                         |
                                     ------------------- concept:Information -----------------
                                                                  ^
                                                                  |
                                                                .....

Unfortunately, I ran into the following problem when using kuno-raeber:Poem in an XML-bulk import:
In case I don't set a value for Poem:hasAuthor, the pre-checker catches me, demanding that I have to provide a value for Poem:hasAuthor. This is something I would expect since kuno-raeber:Text "force" the usage of the property 'hasAuthor' for all of its subclasses.

So, when I provide a value for hasAuthor, the consistency-checker stops the import with an 

    Post failed {"status":4,"error":"org.knora.webapi.TriplestoreResponseException: Triplestore responded with HTTP code 500 Internal Server Error: org.eclipse.rdf4j.query.UpdateExecutionException: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: com.ontotext.trree.consistency.ConsistencyException: Consistency check cardinality_1_not_greater_with_deletion_flag_0 failed: -error, 

which I totally don't understand.
Therefore I face the following situation: 

        either the xml pre-checker throws an error, or the consistency-checker does.

From the logical point of view (inheritance), I would support the pre-checker, but anyhow, I currently stuck into a deadlock.

Do you have any suggestions? I hope the attached files, clears something up (sorry, but the 'with_Poem-hasAuthor) example needs to run in combination with salsah) 

Thank you very much in advance.

Best,
Sascha

[import-deadlock.zip](https://github.com/dhlab-basel/Knora/files/2314502/import-deadlock.zip)

**Comment by benjamingeer** [comment]
Thank you very much for this great bug report. I can explain what's happening. In your example that includes `text:hasAuthor`, you have:

```xml
  <p004D-kuno-raeber:PublicationPoem id="Raeber.Poem-00001">
    <knoraXmlImport:label>Worte</knoraXmlImport:label>
    <p004D-kuno-raeber:p0048-human__creationHasDate knoraType="date_value">GREGORIAN:1981-06-30</p004D-kuno-raeber:p0048-human__creationHasDate>
    <p004D-kuno-raeber:p0048-human__hasModificationDate knoraType="date_value">GREGORIAN:2015-02-15</p004D-kuno-raeber:p0048-human__hasModificationDate>
    <p004D-kuno-raeber:hasStrophe knoraType="boolean_value">false</p004D-kuno-raeber:hasStrophe>
    <p004D-kuno-raeber:isFinalVersion knoraType="boolean_value">true</p004D-kuno-raeber:isFinalVersion>
    <p004D-kuno-raeber:isInSwissGerman knoraType="boolean_value">false</p004D-kuno-raeber:isInSwissGerman>
    <p004D-kuno-raeber:isPartOfCycle knoraType="boolean_value">false</p004D-kuno-raeber:isPartOfCycle>
    <p004D-kuno-raeber:poemHasTitle knoraType="richtext_value">Worte</p004D-kuno-raeber:poemHasTitle>
    <p004D-kuno-raeber:p0050-literature__hasPoet>
      <p0048-human:Person knoraType="link_value" linkType="ref" target="Raeber.Person-Kuno_Raeber"/>
    </p004D-kuno-raeber:p0050-literature__hasPoet>
    <p004D-kuno-raeber:p0056-publishing__hasLastAuthorizedPublication>
      <p0056-publishing:Publication knoraType="link_value" linkType="ref" target="Raeber.Convolute-00009"/>
    </p004D-kuno-raeber:p0056-publishing__hasLastAuthorizedPublication>
    <p004D-kuno-raeber:p0056-publishing__hasNachlassPublicationDescription knoraType="richtext_value">Bd.1, 191</p004D-kuno-raeber:p0056-publishing__hasNachlassPublicationDescription>
    <p004D-kuno-raeber:p0056-publishing__hasPublicationNumber knoraType="int_value">001</p004D-kuno-raeber:p0056-publishing__hasPublicationNumber>
    <p004D-kuno-raeber:p0056-publishing__isPublishedIn>
      <p0056-publishing:Publication knoraType="link_value" linkType="ref" target="Raeber.Convolute-00009"/>
    </p004D-kuno-raeber:p0056-publishing__isPublishedIn>
    <p004D-kuno-raeber:p0059-text__hasAlias knoraType="richtext_value">worte</p004D-kuno-raeber:p0059-text__hasAlias>
    <p004D-kuno-raeber:p0059-text__hasAuthor>
      <p0048-human:Person knoraType="link_value" linkType="ref" target="Raeber.Person-Kuno_Raeber"/>
    </p004D-kuno-raeber:p0059-text__hasAuthor>
    <p004D-kuno-raeber:p0059-text__hasPageNumberDescription knoraType="richtext_value">11</p004D-kuno-raeber:p0059-text__hasPageNumberDescription>
    <p004D-kuno-raeber:p005A-text-editing__hasDerivedTextExpression>
      <p005A-text-editing:DerivedTextExpression knoraType="link_value" linkType="ref" target="Raeber.DerivedTextExpression-00001"/>
    </p004D-kuno-raeber:p005A-text-editing__hasDerivedTextExpression>
    <p004D-kuno-raeber:knoraXmlImport__seqnum knoraType="int_value">1</p004D-kuno-raeber:knoraXmlImport__seqnum>
  </p004D-kuno-raeber:PublicationPoem>
```

Here you give a value for `<p004D-kuno-raeber:p0050-literature__hasPoet>` and a value for `<p004D-kuno-raeber:p0059-text__hasAuthor>`. But the consistency constraint on `text:hasAuthor` forbids this. Since `litera:hasPoet` is a subproperty of `text:hasAuthor`, and `kuno-raeber:Text` has cardinality `1` on `text:hasAuthor`, a `kuno-raeber:Poem` cannot have distinct values for `text:hasAuthor` and `litera:hasPoet`. This is why the GraphDB consistency checker complains.

The XML import schema generated for the `kuno-raeber` ontology allows distinct values for `text:hasAuthor` and `litera:hasPoet` in `PublicationPoem`, and this is clearly wrong. The question is, what should Knora do in this case?

Knora's inheritance rule is that subclasses can override cardinalities in superclasses, but here we have a case where a subclass inherits two incompatible cardinalities from two different superclasses.

It would not be possible for Knora to say that the cardinality `0-n` on `litera:hasPoet` overrides the cardinality `1` on `text:hasAuthor`, because `0-n` is less restrictive than `1`. Following RDFS inference rules, the GraphDB consistency checker would still insist that both cardinalities should be respected, which means that the most restrictive cardinality would still be enforced. This is why Knora doesn't allow cardinalities to be overridden in a way that would make them less restrictive.

Therefore I think the only option is for Knora to forbid this situation when it checks ontologies for validity. In other words, if P1 is a subproperty of P2, a class should not be allowed to have a cardinality on P1 as well as a more restrictive cardinality on P2.

I would even suggest that if P1 is a subproperty of P2, a class should not be allowed to have cardinalities for both P1 and P2, regardless of how restrictive those cardinalities are. Suppose we changed the cardinality on `text:hasAuthor` to be `0-n`, like `litera:hasPoet`. The `Poem` class would still inherit both cardinalities, and your import would work as is. But this would mean that you could submit two different values for `text:hasAuthor` and `litera:hasPoet`. It seems to me that this wouldn't make any sense. How could the poet and the author be two different people?

Allowing both a property and a subproperty would also create problems for Salsah. Suppose `Poem` had cardinality `1-n` on `text:hasAuthor`, and cardinality `1-n` on `litera:hasPoet`. Salsah's form for creating a `Poem` resource would show both properties, and it would require you to fill in two separate values for them, even though technically, just entering a value for `litera:hasPoet` should satisfy the cardinality on `text:hasAuthor`.

Therefore I suggest that Knora should not allow a class to have a cardinality on property P and on a subproperty of P.

@lrosenth do you agree?

**Comment by sacha-alex** [comment]
I am not sure about the whole thing, it doesn't convince me completely.  From a technical point of view, I think that the current model is correct, in a sense that (in this case) every poem must have an author and can have any number of poets. The meaning that a poet has always been the same person as an author is just a special case. (Think e.g. at a speech, where there must be exactly one speaker, but there might be also some ghostwriters that are working behind the scene...).

What worries me most is the fact that I can't detect a pattern, how Knora/GraphDB handles the queries/do the checks.

I dug a little bit deeper and did some experiments with the following results:
  - I am allowed to modify 'cardinality=1' into 'minCardinality=1', and can import the stuff completely
  - I am not allowed to modify 'cardinality=1' into 'maxCardinality=1' or use a combination of minCard=maxCard=1. In both cases, I am able to upload the ontology into GraphDB without an error, but get one when later in the export process.
  - What worries me the most is that, given the unmodified ontology (hasAuthor:card=1), I am able to import all records, when I abandon the 'hasPoet' property (leave it empty) and just use the 'hasAuthor' property.
 
The first two cases might imply that there might be a problem with the maxCardinality, how it is defined internally and if the assumption cardinality=x => minCard=maxCard=x is true.
But this doesn't explain (to me) the behavior in the third case.

At the moment, I get rid of the problem by using the first 'solution', using minCardinality=1
another one, the most radical one, might be not using cardinalities at all by using minCardinality=0 globally.

**Comment by benjamingeer** [comment]
> every poem must have an author and can have any number of poets

What does that mean? Aren't the poets authors? Can there be a poet who is not an author?

> Think e.g. at a speech, where there must be exactly one speaker, but there might be also some ghostwriters that are working behind the scene

Then a speech could have properties `hasSpeaker` and `hasGhostwriter`, both of which could be subproperties of `hasAuthor`. But it would not need to have `hasSpeaker` and `hasAuthor`.

> I am allowed to modify 'cardinality=1' into 'minCardinality=1', and can import the stuff completely

Because then it becomes OK (for the GraphDB consistency checker) have two authors, one of whom is also a poet.

> I am not allowed to modify 'cardinality=1' into 'maxCardinality=1' or use a combination of minCard=maxCard=1. In both cases, I am able to upload the ontology into GraphDB without an error, but get one when later in the export process.

Our GraphDB consistency checking rules don't check ontologies at all, only data. Only Knora checks ontologies. The bug here is that Knora isn't rejecting an illogical class definition.

If you use `maxCardinality 1` instead of `cardinality 1` on `hasAuthor`, you will violate exactly the same consistency rule as in your initial example. The implementation of `cardinality 1` in the GraphDB consistency checker is simply a combination of `minCardinality 1` and `maxCardinality 1`.

> What worries me the most is that, given the unmodified ontology (hasAuthor:card=1), I am able to import all records, when I abandon the 'hasPoet' property (leave it empty) and just use the 'hasAuthor' property.

This is a logical consequence of your cardinalities. You have `minCardinality 0` on `hasPoet`. This means that it is optional.

**Comment by sacha-alex** [comment]
Thanks, Ben for the detailed explanation. That makes it much clearer for me.
